window.NAMES_ES = {
  "AA_01": "Androide",
  "AB_01": "Necrobot",
  "AC_01": "Humanoide Perfido",
  "AD_01": "Escarabot",
  "AE_01": "Coloso",
  "AF_01": "Deus Machina",
  "B_01": "Zombi",
  "BA_01": "Zomborg",
  "BB_01": "Lord Blood",
  "BC_01": "Despota Negro",
  "BD_01": "Necrodragon",
  "BE_01": "Fantasmonauta",
  "BF_01": "Baron Lundi",
  "C_01": "Guerrero",
  "CA_01": "Ejecutor",
  "CB_01": "Banshee Guerrera",
  "CC_01": "Caballero Nordico",
  "CD_01": "Honey Bunny",
  "CE_01": "Marciano Errante",
  "CF_01": "Valkiria",
  "D_01": "Bestia",
  "DA_01": "Reptoide",
  "DB_01": "Cerbero",
  "DC_01": "Rakshasa",
  "DD_01": "Kaiju Kitty",
  "DE_01": "Reina Parasita",
  "DF_01": "Dracus Nobilis",
  "E_01": "Extraterrestre",
  "EA_01": "Aniquilador",
  "EB_01": "Tutti Viscosi",
  "EC_01": "Sundance Bug",
  "ED_01": "Xenos",
  "EE_01": "Astrosurfista",
  "EF_01": "Nebulon",
  "F_01": "Diablesa",
  "FA_01": "Tecno Tao",
  "FB_01": "La Parca",
  "FC_01": "Gandolphus",
  "FD_01": "Medusa",
  "FE_01": "C'thlig",
  "FF_01": "Señor del Abismo",
  "A_01": "Robot",
  "AA_02": "Goliat",
  "AB_02": "Hypnos",
  "AC_02": "Capitan Mecano",
  "AD_02": "Monocerus",
  "AE_02": "Libraro",
  "AF_02": "Virgon",
  "BA_02": "Muñeca Diabolica",
  "BB_02": "Espectro de la Cripta",
  "BC_02": "Capitan Osamenta",
  "BD_02": "Cancernia",
  "BE_02": "Caprika",
  "BF_02": "Mago Tetrico",
  "CA_02": "Interceptrix",
  "CB_02": "Bushi",
  "CC_02": "Buck Maurice",
  "CD_02": "Sagitauro",
  "CE_02": "Geminium",
  "CF_02": "Thor",
  "DA_02": "Aracno",
  "DB_02": "Zombat",
  "DC_02": "Leohart",
  "DD_02": "Maestro Splitter",
  "DE_02": "Cosmo Kong",
  "DF_02": "Satiro Hechicero",
  "EA_02": "Sentry",
  "EB_02": "Sirenia",
  "EC_02": "Behemoth",
  "ED_02": "Rocageno",
  "EE_02": "Supernovus",
  "EF_02": "Mr Marvelous",
  "FA_02": "Mekali",
  "FB_02": "Principe Escorpion",
  "FC_02": "Capitan Paz",
  "FD_02": "Horus",
  "FE_02": "Azuria",
  "FF_02": "Castigo",
  "AA_03": "H.U.M.A.N.",
  "AB_03": "Xenarach",
  "AC_03": "Dezinger",
  "AD_03": "Tauridus",
  "AE_03": "Invadron",
  "AF_03": "Barbaroca",
  "BA_03": "Triple-B",
  "BB_03": "Motero Maldito",
  "BC_03": "Micky Krueger",
  "BD_03": "Oso Espantoso",
  "BE_03": "Quebrantacuellos",
  "BF_03": "Carnero Vengador",
  "CA_03": "General Caos",
  "CB_03": "Ragnar",
  "CC_03": "Zena",
  "CD_03": "Haggis",
  "CE_03": "Guardian Galactico",
  "CF_03": "Hada Machete",
  "DA_03": "Mantidroide",
  "DB_03": "Cobrakai",
  "DC_03": "Gargantus",
  "DD_03": "Psicojabali",
  "DE_03": "Armadizo",
  "DF_03": "Absolem",
  "EA_03": "Exopez",
  "EB_03": "Devorador",
  "EC_03": "Star Trooper",
  "ED_03": "Wampara",
  "EE_03": "Maestro Oida",
  "EF_03": "Aquapunzel",
  "FA_03": "Bazzinger",
  "FB_03": "Anubis",
  "FC_03": "Oriax",
  "FD_03": "Ivory Hanzo",
  "FE_03": "Astromago",
  "FF_03": "Mandragora",
  "A_03": "Garuda",
  "B_03": "Jack O'Lantern",
  "C_03": "Frostmass",
  "D_03": "Rambit",
  "E_03": "Ceres",
  "F_03": "Mago de las Nieves",
  "AA_04": "Oculus",
  "AB_04": "Commander Ender",
  "AC_04": "El Fontanero",
  "AD_04": "Malvatron",
  "AE_04": "Supraman X",
  "AF_04": "Autonoraptor",
  "BA_04": "El Experimento",
  "BB_04": "Sacamantecas",
  "BC_04": "George Washington",
  "BD_04": "Dama Harpia",
  "BE_04": "Capitan Perla Negra",
  "BF_04": "Emperador Galactico",
  "CA_04": "Project X27",
  "CB_04": "Leonidas",
  "CC_04": "Lara",
  "CD_04": "Battle Toad",
  "CE_04": "Zortrex",
  "CF_04": "Azog",
  "DA_04": "Escuadron Rhino",
  "DB_04": "Louis XVI",
  "DC_04": "Cezanne",
  "DD_04": "Cernunnos",
  "DE_04": "Genshiryoku",
  "DF_04": "Miroku",
  "EA_04": "Brick McGole",
  "EB_04": "Matafantasmas",
  "EC_04": "Santactopus",
  "ED_04": "Mapach Wik",
  "EE_04": "Flying Jordson",
  "EF_04": "Mephisto",
  "FA_04": "Banker",
  "FB_04": "Bruja Malvada",
  "FC_04": "Mexihcatl",
  "FD_04": "Buranka",
  "FE_04": "Space Princess",
  "FF_04": "Monolith",
  "B_04": "Cuervo",
  "F_04": "Leprechaun",
  "AA_05": "Tecnoforzer",
  "AB_05": "Neo Urban XIII",
  "AC_05": "Ciberpunk",
  "AD_05": "Cibercroc",
  "AE_05": "Ciberbabosa",
  "AF_05": "Abraham Lincoln",
  "BA_05": "Doctor Blaw",
  "BB_05": "Caronte",
  "BC_05": "Loco de la Motosierra",
  "BD_05": "Bulldozer",
  "BE_05": "Nyrlatoth",
  "BF_05": "Britany",
  "CA_05": "Challengeer",
  "CB_05": "Cupido",
  "CC_05": "Shin Hakuho",
  "CD_05": "Hog the Ripper",
  "CE_05": "Sun-Duke",
  "CF_05": "Monje Akuso",
  "DA_05": "Fenec Plus Ultra",
  "DB_05": "Brawler",
  "DC_05": "Rey Mono",
  "DD_05": "Pejelagarto",
  "DE_05": "Exo Cookie",
  "DF_05": "Madre de los Dragones",
  "EA_05": "Rey Steven",
  "EB_05": "Marine Muerto",
  "EC_05": "Cazador Espacial",
  "ED_05": "Acarius",
  "EE_05": "Jhingal",
  "EF_05": "Kraken",
  "FA_05": "Chaman Sombra",
  "FB_05": "Hardcorius",
  "FC_05": "Yelda",
  "FD_05": "Artista Siniestro",
  "FE_05": "Nebulus",
  "FF_05": "Glubber",
  "A_05": "Cazarrecompensas",
  "B_05": "Drudge Zombie",
  "C_05": "Barbaro",
  "AA_06": "Hercules",
  "AB_06": "Drusella",
  "AC_06": "Viper",
  "AD_06": "Bioerizo",
  "AE_06": "Marv",
  "AF_06": "Duplicado de Eva",
  "BA_06": "Z-0",
  "BB_06": "Gloton",
  "BC_06": "Dandi oscar",
  "BD_06": "Tyrtiduron",
  "BE_06": "Apofis",
  "BF_06": "El Rey de Mimphys",
  "CA_06": "ERR-ADI-K-Bot",
  "CB_06": "Artemisa",
  "CC_06": "El Gringo",
  "CD_06": "Gladiadog",
  "CE_06": "Tomahawk",
  "CF_06": "Tio Sam",
  "DA_06": "Triceratanque",
  "DB_06": "Casto",
  "DC_06": "Comeabuelas",
  "DD_06": "Mama Kangu",
  "DE_06": "Darwin",
  "DF_06": "Sable",
  "EA_06": "Krunk",
  "EB_06": "Garlog",
  "EC_06": "Zeus",
  "ED_06": "Mau-Jack",
  "EE_06": "Reina Rakkti",
  "EF_06": "Mandor",
  "FA_06": "Lily",
  "FB_06": "Hechicera",
  "FC_06": "Borrasca",
  "FD_06": "Kung Chow",
  "FE_06": "Dollbyte",
  "FF_06": "Namaste",
  "AA_07": "Proyecto 3V3",
  "AB_07": "Aplastador",
  "AC_07": "Robofuerte",
  "AD_07": "Avispa Diesel",
  "AE_07": "Alfie",
  "AF_07": "Bounda",
  "BA_07": "Pikabu",
  "BB_07": "Necroparasito",
  "BC_07": "Turbacieno",
  "BD_07": "El Original",
  "BE_07": "Nezarim",
  "BF_07": "Champicorteza",
  "CA_07": "Rocky Botboa",
  "CB_07": "Rey Esqueleto",
  "CC_07": "Spartac",
  "CD_07": "Juan Hielo",
  "CE_07": "Aran",
  "CF_07": "Mega Claus",
  "DA_07": "Carlingger",
  "DB_07": "Señor Dragon",
  "DC_07": "Noren",
  "DD_07": "Globomono",
  "DE_07": "Capitan Gluglu",
  "DF_07": "Quimera",
  "EA_07": "Capitan Patriota",
  "EB_07": "Starminator",
  "EC_07": "Falcon",
  "ED_07": "Paramic",
  "EE_07": "Astro Gummy",
  "EF_07": "Kal Wayne",
  "FA_07": "Dr. Frost",
  "FB_07": "Las Moiras",
  "FC_07": "Amarok",
  "FD_07": "Fenix",
  "FE_07": "Rey de los Insectos",
  "FF_07": "Geomega",
  "AA_08": "Centinela R0B-H4N",
  "AB_08": "Gran Señor de las Tumbas",
  "AC_08": "Blender",
  "AD_08": "Kitty Ranger",
  "AE_08": "Andromeda",
  "AF_08": "H0ud1n1",
  "BA_08": "Naraxis",
  "BB_08": "Bruja de la Peste",
  "BC_08": "Thran",
  "BD_08": "Enano y Cerebro",
  "BE_08": "Dug Dario",
  "BF_08": "Van Helsing",
  "CA_08": "Makino",
  "CB_08": "Wrath",
  "CC_08": "Yokozuna",
  "CD_08": "Drall",
  "CE_08": "El Rey sin Nombre",
  "CF_08": "Wynn",
  "DA_08": "Asaylan",
  "DB_08": "Tiranozomb",
  "DC_08": "Sanik",
  "DD_08": "Rinotauro",
  "DE_08": "Cosmopandas",
  "DF_08": "Chantecler",
  "EA_08": "Lady Libertad",
  "EB_08": "Dr. Nucleus",
  "EC_08": "Espectra",
  "ED_08": "Sgt. Pandamonium",
  "EE_08": "Golemagnus",
  "EF_08": "Seiyatsu",
  "FA_08": "FootBot",
  "FB_08": "Gozer",
  "FC_08": "Kudamono",
  "FD_08": "Omikami",
  "FE_08": "Majin Zam",
  "FF_08": "Tormenta de Fuego",
  "AA_09": "H.U.N.T.3.R",
  "AB_09": "Grumpy Claus",
  "AC_09": "Optimus Zord",
  "AD_09": "Carcinus Gigas",
  "AE_09": "Centaurus",
  "AF_09": "Caudillo Steam",
  "BA_09": "Excavalipsis",
  "BB_09": "Frankenhuahua",
  "BC_09": "El Coleccionista",
  "BD_09": "Faucesnegras",
  "BE_09": "Pirotropo",
  "BF_09": "Calaca",
  "CA_09": "Big Bo$$",
  "CB_09": "Jane Saw",
  "CC_09": "Lancelot",
  "CD_09": "Mon-Key Crew",
  "CE_09": "Zar Bomba",
  "CF_09": "Amo de las Llaves",
  "DA_09": "Sound Killah",
  "DB_09": "Horax",
  "DC_09": "Maestro Shinzo",
  "DD_09": "Mister T-Ger",
  "DE_09": "Zigmo",
  "DF_09": "Quetzalcoatl",
  "EA_09": "Capitan Gorn",
  "EB_09": "Reina Sylvidra",
  "EC_09": "Excaliduro",
  "ED_09": "Rox McRain",
  "EE_09": "Megastral",
  "EF_09": "Mago Ryzafredd",
  "FA_09": "Zenguru",
  "FB_09": "Hadeath",
  "FC_09": "Gorthaur el Cruel",
  "FD_09": "Dracomago",
  "FE_09": "Xeleroth",
  "FF_09": "Liquidador",
  "AA_10": "ED-404",
  "AB_10": "S-K-Venger",
  "AC_10": "Sargento Dusk",
  "AD_10": "Hipopotanque",
  "AE_10": "Akai-Bot",
  "AF_10": "El Veneno",
  "BA_10": "Hellsaw",
  "BB_10": "T-3rr0r",
  "BC_10": "King Lulu",
  "BD_10": "Waryena",
  "BE_10": "Overkill",
  "BF_10": "El Enterrador",
  "CA_10": "Altaris",
  "CB_10": "Frankendwarf",
  "CC_10": "Urgan",
  "CD_10": "Guardia Men'ki",
  "CE_10": "Capitan Achabe",
  "CF_10": "Arelvam",
  "DA_10": "Hawkeye",
  "DB_10": "Buffalor",
  "DC_10": "Krampus",
  "DD_10": "Kameo",
  "DE_10": "Mad Mike",
  "DF_10": "Gwenn",
  "EA_10": "Surfista del Espacio",
  "EB_10": "Gakarian",
  "EC_10": "Gamallia",
  "ED_10": "Angry Pork",
  "EE_10": "E.T.-Liot",
  "EF_10": "Divastator",
  "FA_10": "Mimi Cronocurva",
  "FB_10": "Yggdrasil",
  "FC_10": "Hefesto",
  "FD_10": "Master Paw",
  "FE_10": "Bahamut",
  "FF_10": "Bregbeam",
  "AA_11": "TriAD",
  "AB_11": "Enviro 3.0",
  "AC_11": "Spin Fury",
  "AD_11": "Mecaovoide Aracneo",
  "AE_11": "Mix0-Logo",
  "AF_11": "Heimdall",
  "BA_11": "Roadmaster",
  "BB_11": "La Olvidada",
  "BC_11": "Colmillo Rabioso",
  "BD_11": "Cooktouille",
  "BE_11": "Oculys",
  "BF_11": "Aqueronte",
  "CA_11": "The Reef",
  "CB_11": "Disension",
  "CC_11": "Santagonista",
  "CD_11": "Sir Bannog",
  "CE_11": "Chun-Lei",
  "CF_11": "Caliburn EX",
  "DA_11": "An0malie",
  "DB_11": "Piwisher",
  "DC_11": "Spada",
  "DD_11": "Terror Abisal",
  "DE_11": "Drei, Space Corgi",
  "DF_11": "Chocolem",
  "EA_11": "Dreadnought",
  "EB_11": "Aubraea Mutantula",
  "EC_11": "Veren Kaeesu",
  "ED_11": "Owlock",
  "EE_11": "Asteroide Gestalt",
  "EF_11": "Dimentio",
  "FA_11": "Orion",
  "FB_11": "Pesadilla Viviente",
  "FC_11": "Midas",
  "FD_11": "Ishi no Ōkami",
  "FE_11": "Pierrot",
  "FF_11": "Gerard Steelgarden",
  "AA_12": "Cabloide",
  "AB_12": "Disfuncidroide",
  "AC_12": "Phileas Derocas",
  "AD_12": "Lepidoptech",
  "AE_12": "Tenacity",
  "AF_12": "Protector de los Sueños",
  "BA_12": "Cr€$u$",
  "BB_12": "Doctor del Farol",
  "BC_12": "Caronte (Halloween)",
  "BD_12": "Thanaconda",
  "BE_12": "Gelatina Purulenta",
  "BF_12": "Clerigo Oscuro",
  "CA_12": "General Terracota",
  "CB_12": "Ballesto",
  "CC_12": "Scaramouche",
  "CD_12": "Capitan aguila",
  "CE_12": "Regulo&Juzya",
  "CF_12": "Heredero de los 5 anillos",
  "DA_12": "Tecnocaracol",
  "DB_12": "Gran Gusano de los Tuneles",
  "DC_12": "Zapador de Madrigueras",
  "DD_12": "Lampyrion Solar",
  "DE_12": "Leviatan",
  "DF_12": "Basilisco y Esdragon",
  "EA_12": "Bricodron LLK-215",
  "EB_12": "Medico Astral",
  "EC_12": "Litominero Stellariano",
  "ED_12": "Ammonia Atlantica",
  "EE_12": "Polaris",
  "EF_12": "X'astuth",
  "FA_12": "Cibermantico Etereo",
  "FB_12": "Dama del Crepusculo",
  "FC_12": "Generalisimo Chocoleon IV",
  "FD_12": "Simurgh",
  "FE_12": "Exoceleste algido",
  "FF_12": "Archivista Eterno",
  "B_12": "Huesamblaje",
  "D_12": "Aullosaurio",
  "E_12": "Explorador Sideral",
  "F_12": "Invocador",
  "AA_13": "TCB-8566 Trafficroid",
  "AB_13": "El Arquitecto",
  "AC_13": "Capsuladora MTZ-004",
  "AD_13": "Myrmidus.exe",
  "AE_13": "Helidron KxT-271",
  "AF_13": "Golem de Epocas",
  "BA_13": "La Anárquica",
  "BB_13": "El Fosforescente",
  "BC_13": "Doctor Desollador",
  "BD_13": "Sangresquito",
  "BE_13": "Viajero de Vortice",
  "BF_13": "Amalgalmas",
  "CA_13": "Anteros",
  "CB_13": "El Motin",
  "CC_13": "Amistad Sin Limites",
  "CD_13": "Bearsikk Sikleast",
  "CE_13": "Atlas",
  "CF_13": "Hijo de la Tormenta",
  "DA_13": "Antropobot Soñador",
  "DB_13": "El Descolorido",
  "DC_13": "Sierrametrodon",
  "DD_13": "Llama Sensei",
  "DE_13": "Oryctolagus Exobioicus",
  "DF_13": "Emperador Helado",
  "EA_13": "Peregrino Espacial",
  "EB_13": "Xinomas",
  "EC_13": "Hekantocheiros",
  "ED_13": "Medinosaurio",
  "EE_13": "Nexo Orbital",
  "EF_13": "Achernar",
  "FA_13": "Helicoide Boreal",
  "FB_13": "Altísimo Candelabro",
  "FC_13": "Rey De Avalon",
  "FD_13": "Tezcatlipoca",
  "FE_13": "Vivaldi",
  "FF_13": "Sakuraboshi",
  "A_13": "Asimov",
  "B_13": "GAR, Zombi Soberano",
  "C_13": "D'Arathomis",
  "D_13": "Sasquatch",
  "E_13": "Astrobservador",
  "F_13": "Väinämöinen",
  "AA_99": "A00-C0R3-C0NTR0L",
  "AB_99": "Simulacro de Combate",
  "AE_99": "Azaronimo",
  "AF_99": "A027441",
  "BD_99": "Tengu",
  "CA_99": "Missy Despierta",
  "CE_99": "Kolossus",
  "CF_99": "Reed, El Verdadero Heroe",
  "DF_99": "Genimal",
  "EA_99": "Termodroide Celsius",
  "EB_99": "Diablo",
  "ED_99": "Octopia",
  "EE_99": "Animus de Irrealidad",
  "EF_99": "Mago de la Singularidad",
  "FA_99": "Arcangel",
  "FC_99": "Nimrod",
  "FE_99": "Ingeniero",
  "FF_99": "Mascarada Emocional",
  "AB_14": "El Presentador",
  "AC_14": "Professor Cronomantico",
  "AD_14": "Origamix",
  "AE_14": "Giganto-Moai",
  "AF_14": "Black I.C.E.",
  "BA_14": "Mecargola",
  "BC_14": "Traiciobaza",
  "BD_14": "Lapin Zombie",
  "CA_14": "Breakmaster",
  "CB_14": "Capitan Barbanegra",
  "CC_14": "Rey Azul",
  "CD_14": "Don Gamberetti",
  "CF_14": "Hielo Patinadora Yria",
  "DA_14": "B.U.N. Genio",
  "DB_14": "La Locura Reptante",
  "DC_14": "Terror Jurasico",
  "DD_14": "Señor Bestial",
  "DE_14": "Infinito Supermasivo",
  "EA_14": "D.A.B.",
  "ED_14": "Hidrira",
  "EF_14": "K'yu T'ypaï",
  "FB_14": "Zagam, Gran Rey De La Avaricia",
  "FD_14": "Freyja, Reina de los Vanir",
  "FE_14": "Núcleo seráfico",
  "FF_14": "Profeta del Crepúsculo",
  "A_14": "Automata",
  "B_14": "Espectroplasma",
  "C_14": "Gladiador",
  "E_14": "Spiraxia",
  "BF_14": "Irradiancia",
  "F_14": "Mago",
  "DE_15": "Estrellador Telurico",
  "AB_15": "El Glitchy Corazón"
};

window.getMutantName = function(mutant, lang) {
  if (!mutant) return '';
  const l = lang || (typeof MGG !== 'undefined' ? MGG.state.lang : 'en');
  if (l === 'es' && mutant.id && window.NAMES_ES[mutant.id]) {
    return window.NAMES_ES[mutant.id];
  }
  return mutant.name || '';
};
