/* ── Spanish name helper ────────────────────────────── */
function _rbGetName(mutant) {
  if (typeof window.getMutantName === 'function') return window.getMutantName(mutant);
  return mutant.name || '';
}

document.addEventListener('DOMContentLoaded', function () {

  /* ── DATA ─────────────────────────────────────────── */
  const ALL_REBALANCE_DATA = [
        {
      title: "Mutantes Rebalanceados - Julio 2026",
      mutants: [
        { "name": "A00-C0R3-C0NTR0L", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_aa_99.png", "changes": [{"stat":"AbilityPower+","oldValue":"55","newValue":"65"},{"stat":"Life","oldValue":"4621","newValue":"4821"},{"stat":"Atk1+","oldValue":"1861","newValue":"1981"},{"stat":"Atk2+","oldValue":"1022:AOE","newValue":"1222:AOE"}] },
        { "name": "Anteros", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_ca_13.png", "changes": [{"stat":"AbilityPower","oldValue":"17","newValue":"25"},{"stat":"AbilityPower+","oldValue":"32","newValue":"40"},{"stat":"Life","oldValue":"3434","newValue":"3834"},{"stat":"Atk1+","oldValue":"1669","newValue":"1869"},{"stat":"Atk2+","oldValue":"1669","newValue":"1869"}] },
        { "name": "Archangel", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_fa_99.png", "changes": [{"stat":"Life","oldValue":"4076","newValue":"5076"},{"stat":"Atk1+","oldValue":"1862","newValue":"2262"},{"stat":"Atk2+","oldValue":"1862","newValue":"2262"}] },
        { "name": "Awakened Missy", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_ca_99.png", "changes": [{"stat":"AbilityPower","oldValue":"10","newValue":"15"},{"stat":"AbilityPower+","oldValue":"15","newValue":"20"},{"stat":"Life","oldValue":"2512","newValue":"2812"},{"stat":"Atk1","oldValue":"1200","newValue":"1400"},{"stat":"Atk1+","oldValue":"2421","newValue":"2721"},{"stat":"Atk2","oldValue":"1200","newValue":"1400"},{"stat":"Atk2+","oldValue":"2421","newValue":"2721"}] },
        { "name": "Basilisc&Tarragon", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_df_12.png", "changes": [{"stat":"AbilityPower+","oldValue":"38","newValue":"40"},{"stat":"Life","oldValue":"3333","newValue":"4033"},{"stat":"Atk1","oldValue":"921","newValue":"1123"},{"stat":"Atk1+","oldValue":"1381","newValue":"1981"},{"stat":"Atk2","oldValue":"921","newValue":"1123"},{"stat":"Atk2+","oldValue":"1381","newValue":"1981"}] },
        { "name": "Boreal Helix", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_fa_13.png", "changes": [{"stat":"AbilityPower","oldValue":"-24","newValue":"24"},{"stat":"AbilityPower+","oldValue":"-60","newValue":"70"},{"stat":"Atk1+","oldValue":"1138","newValue":"1638"},{"stat":"Atk2+","oldValue":"844:AOE","newValue":"1044:AOE"}] },
        { "name": "Calaca", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_bf_09.png", "changes": [{"stat":"Life","oldValue":"4348","newValue":"4548"},{"stat":"Atk1","oldValue":"1469","newValue":"1569"},{"stat":"Atk1+","oldValue":"2204","newValue":"2304"},{"stat":"Atk2","oldValue":"1469","newValue":"1569"},{"stat":"Atk2+","oldValue":"2204","newValue":"2304"}] },
        { "name": "Captain Eagle", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_cd_12.png", "changes": [{"stat":"AbilityPower","oldValue":"-20","newValue":"20"},{"stat":"AbilityPower+","oldValue":"-30","newValue":"40"},{"stat":"Life","oldValue":"3494","newValue":"3794"}] },
        { "name": "Cryonos", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_c_03.png", "changes": [{"stat":"AbilityPower","oldValue":"-15","newValue":"15"},{"stat":"AbilityPower+","oldValue":"-25","newValue":"33"},{"stat":"Atk1+","oldValue":"1597","newValue":"1897"},{"stat":"Atk2+","oldValue":"918:AOE","newValue":"1158:AOE"}] },
        { "name": "Ctopy", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_ed_99.png", "changes": [{"stat":"Life","oldValue":"4497","newValue":"4697"},{"stat":"Atk1","oldValue":"1034","newValue":"1134"},{"stat":"Atk1+","oldValue":"1577","newValue":"1677"},{"stat":"Atk2","oldValue":"525:AOE","newValue":"565:AOE"},{"stat":"Atk2+","oldValue":"788:AOE","newValue":"988:AOE"}] },
        { "name": "Darwin", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_de_06.png", "changes": [{"stat":"AbilityPower+","oldValue":"38","newValue":"41"},{"stat":"Life","oldValue":"3315","newValue":"3615"}] },
        { "name": "Diablo", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_eb_99.png", "changes": [{"stat":"AbilityPower","oldValue":"20","newValue":"23"},{"stat":"AbilityPower+","oldValue":"30","newValue":"34"},{"stat":"Atk1+","oldValue":"2394","newValue":"2494"},{"stat":"Atk2+","oldValue":"2394","newValue":"2494"}] },
        { "name": "Emotional Maskerade", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_ff_99.png", "changes": [{"stat":"AbilityPower","oldValue":"-24","newValue":"27"},{"stat":"AbilityPower+","oldValue":"-37","newValue":"39"},{"stat":"Atk1+","oldValue":"2631","newValue":"2731"},{"stat":"Atk2+","oldValue":"1811:AOE","newValue":"1911:AOE"}] },
        { "name": "Garuda", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_a_03.png", "changes": [{"stat":"AbilityPower","oldValue":"20","newValue":"30"},{"stat":"AbilityPower+","oldValue":"45","newValue":"50"},{"stat":"Atk1","oldValue":"432","newValue":"632"},{"stat":"Atk1+","oldValue":"876","newValue":"1076"},{"stat":"Atk2","oldValue":"248:AOE","newValue":"448:AOE"},{"stat":"Atk2+","oldValue":"548:AOE","newValue":"748:AOE"}] },
        { "name": "Generalissimo Chocoleon IV", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_fc_12.png", "changes": [{"stat":"AbilityPower","oldValue":"-5","newValue":"5"},{"stat":"AbilityPower+","oldValue":"-40","newValue":"10"},{"stat":"Life","oldValue":"5099","newValue":"5699"}] },
        { "name": "Genimal", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_df_99.png", "changes": [{"stat":"AbilityPower","oldValue":"-20","newValue":"20"},{"stat":"AbilityPower+","oldValue":"-35","newValue":"30"},{"stat":"Atk1","oldValue":"370","newValue":"470"},{"stat":"Atk1+","oldValue":"631","newValue":"1031"},{"stat":"Atk2","oldValue":"370","newValue":"470"},{"stat":"Atk2+","oldValue":"631","newValue":"1031"}] },
        { "name": "Grumpy Claus", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_ab_09.png", "changes": [{"stat":"AbilityPower+","oldValue":"30","newValue":"40"},{"stat":"Speed","oldValue":"4.35","newValue":"4.44"}] },
        { "name": "Hatching Mecharachnidian", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_ad_11.png", "changes": [{"stat":"AbilityPower","oldValue":"-10","newValue":"10"},{"stat":"AbilityPower+","oldValue":"-40","newValue":"60"},{"stat":"Atk1","oldValue":"605","newValue":"805"},{"stat":"Atk1+","oldValue":"605:AOE","newValue":"805:AOE"},{"stat":"Atk2","oldValue":"701","newValue":"791"},{"stat":"Atk2+","oldValue":"1052","newValue":"1182"}] },
        { "name": "Irreality Animus", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_ee_99.png", "changes": [{"stat":"Atk1+","oldValue":"1663","newValue":"1863"},{"stat":"Atk2+","oldValue":"831:AOE","newValue":"1131:AOE"}] },
        { "name": "Ivory Hanzo", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_fd_03.png", "changes": [{"stat":"AbilityPower","oldValue":"-20","newValue":"22"},{"stat":"AbilityPower+","oldValue":"-30","newValue":"33"},{"stat":"Life","oldValue":"1924","newValue":"2424"},{"stat":"Atk1+","oldValue":"1545","newValue":"1745"},{"stat":"Atk2+","oldValue":"1545","newValue":"1745"}] },
        { "name": "Jack Ice", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_cd_07.png", "changes": [{"stat":"AbilityPower","oldValue":"-20","newValue":"20"},{"stat":"AbilityPower+","oldValue":"-40","newValue":"40"},{"stat":"Atk1+","oldValue":"1782","newValue":"1982"},{"stat":"Atk2+","oldValue":"1782","newValue":"1984"}] },
        { "name": "Jack O'Lantern", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_b_03.png", "changes": [{"stat":"Atk1+","oldValue":"781","newValue":"1181"},{"stat":"Atk2+","oldValue":"450:AOE","newValue":"750:AOE"}] },
        { "name": "Jurassic Terror", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_dc_14.png", "changes": [{"stat":"AbilityPower","oldValue":"-30","newValue":"30"},{"stat":"AbilityPower+","oldValue":"-60","newValue":"80"},{"stat":"Atk1+","oldValue":"2047","newValue":"2147"},{"stat":"Atk2+","oldValue":"2047","newValue":"2147"}] },
        { "name": "K'Yu T'ypaï", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_ef_14.png", "changes": [{"stat":"AbilityPower","oldValue":"-20","newValue":"22"},{"stat":"AbilityPower+","oldValue":"-30","newValue":"33"},{"stat":"Speed","oldValue":"9.09","newValue":"3.22"}] },
        { "name": "Kolossus", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_ce_99.png", "changes": [{"stat":"AbilityPower","oldValue":"-8","newValue":"9"},{"stat":"AbilityPower+","oldValue":"-12","newValue":"13"},{"stat":"Life","oldValue":"5780","newValue":"6031"}] },
        { "name": "Lady Liberty", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_ea_08.png", "changes": [{"stat":"AbilityPower+","oldValue":"30","newValue":"35"},{"stat":"Life","oldValue":"3665","newValue":"3765"}] },
        { "name": "Master Paw", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_fd_10.png", "changes": [{"stat":"AbilityPower","oldValue":"-15","newValue":"15"},{"stat":"AbilityPower+","oldValue":"-25","newValue":"30"},{"stat":"Life","oldValue":"3683","newValue":"3983"},{"stat":"Speed","oldValue":"3.45","newValue":"3.57"}] },
        { "name": "Mecargoyle", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_ba_14.png", "changes": [{"stat":"AbilityPower","oldValue":"-60","newValue":"60"},{"stat":"AbilityPower+","oldValue":"-90","newValue":"110"},{"stat":"Life","oldValue":"2221","newValue":"2421"}] },
        { "name": "Mexihcatl", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_fc_04.png", "changes": [{"stat":"AbilityPower","oldValue":"-15","newValue":"25"},{"stat":"AbilityPower+","oldValue":"-25","newValue":"40"},{"stat":"Life","oldValue":"2445","newValue":"2845"},{"stat":"Atk1+","oldValue":"1048","newValue":"1548"},{"stat":"Atk2+","oldValue":"1048","newValue":"1548"}] },
        { "name": "Perfitrouille", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_bc_14.png", "changes": [{"stat":"AbilityPower","oldValue":"20","newValue":"25"},{"stat":"AbilityPower+","oldValue":"35","newValue":"44"},{"stat":"Speed","oldValue":"9.09","newValue":"9.52"}] },
        { "name": "Polaris", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_ee_12.png", "changes": [{"stat":"AbilityPower","oldValue":"15","newValue":"30"},{"stat":"AbilityPower+","oldValue":"48","newValue":"50"},{"stat":"Atk1+","oldValue":"2231","newValue":"2431"}] },
        { "name": "Randonymous", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_ae_99.png", "changes": [{"stat":"AbilityPower+","oldValue":"32","newValue":"30"},{"stat":"Life","oldValue":"3566","newValue":"3656"},{"stat":"Atk1+","oldValue":"2324","newValue":"2424"},{"stat":"Atk2+","oldValue":"1489:AOE","newValue":"1589:AOE"}] },
        { "name": "Robo Fuerte", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_ac_07.png", "changes": [{"stat":"AbilityPower","oldValue":"-30","newValue":"30"},{"stat":"AbilityPower+","oldValue":"-50","newValue":"50"},{"stat":"Life","oldValue":"2181","newValue":"2381"},{"stat":"Atk1","oldValue":"856","newValue":"956"},{"stat":"Atk1+","oldValue":"1284","newValue":"1494"},{"stat":"Atk2","oldValue":"856","newValue":"956"},{"stat":"Atk2+","oldValue":"1284","newValue":"1494"}] },
        { "name": "Saber", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_df_06.png", "changes": [{"stat":"AbilityPower","oldValue":"-20","newValue":"20"},{"stat":"AbilityPower+","oldValue":"-40","newValue":"50"},{"stat":"Life","oldValue":"3187","newValue":"3487"},{"stat":"Atk1+","oldValue":"1272","newValue":"1472"},{"stat":"Atk2+","oldValue":"1272","newValue":"1472"}] },
        { "name": "Singularity Wizard", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_ef_99.png", "changes": [{"stat":"AbilityPower+","oldValue":"33","newValue":"38"},{"stat":"Life","oldValue":"4101","newValue":"4201"},{"stat":"Atk1+","oldValue":"1128:AOE","newValue":"1158:AOE"},{"stat":"Atk2+","oldValue":"2000","newValue":"2100"}] },
        { "name": "Solar Lampyrion", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_dd_12.png", "changes": [{"stat":"Atk1","oldValue":"1095","newValue":"1295"},{"stat":"Atk1+","oldValue":"1643","newValue":"1943"},{"stat":"Atk2","oldValue":"548:AOE","newValue":"748:AOE"},{"stat":"Atk2+","oldValue":"821:AOE","newValue":"1121:AOE"}] },
        { "name": "Soul Coalescence", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_bf_13.png", "changes": [{"stat":"AbilityPower","oldValue":"-5","newValue":"5"},{"stat":"AbilityPower+","oldValue":"-35","newValue":"45"},{"stat":"Life","oldValue":"4547","newValue":"4847"}] },
        { "name": "Sun-Duke", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_ce_05.png", "changes": [{"stat":"AbilityPower","oldValue":"-20","newValue":"28"},{"stat":"AbilityPower+","oldValue":"-30","newValue":"40"},{"stat":"Life","oldValue":"1405","newValue":"1605"},{"stat":"Speed","oldValue":"6.33","newValue":"4.45"}] },
        { "name": "Supermassive Infinity", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_de_14.png", "changes": [{"stat":"AbilityPower","oldValue":"-30","newValue":"30"},{"stat":"AbilityPower+","oldValue":"-60","newValue":"60"}] },
        { "name": "The Crawling Madness", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_db_14.png", "changes": [{"stat":"AbilityPower","oldValue":"-15","newValue":"15"},{"stat":"AbilityPower+","oldValue":"-40","newValue":"45"},{"stat":"Atk1+","oldValue":"1778","newValue":"2178"},{"stat":"Atk2+","oldValue":"986:AOE","newValue":"1436:AOE"}] },
        { "name": "The Lantern Doctor", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_bb_12.png", "changes": [{"stat":"AbilityPower","oldValue":"-28","newValue":"28"},{"stat":"AbilityPower+","oldValue":"-48","newValue":"48"},{"stat":"Atk1+","oldValue":"2016","newValue":"2316"},{"stat":"Atk2","oldValue":"606:AOE","newValue":"616:AOE"},{"stat":"Atk2+","oldValue":"1432:AOE","newValue":"1552:AOE"}] },
        { "name": "The Reef", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_ca_11.png", "changes": [{"stat":"AbilityPower+","oldValue":"13","newValue":"20"},{"stat":"Life","oldValue":"1277","newValue":"2677"},{"stat":"Atk1+","oldValue":"866","newValue":"1466"},{"stat":"Atk2+","oldValue":"866","newValue":"1466"}] },
        { "name": "Twilight Prophet", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_ff_14.png", "changes": [{"stat":"AbilityPower","oldValue":"25","newValue":"32"},{"stat":"AbilityPower+","oldValue":"40","newValue":"48"},{"stat":"Life","oldValue":"1130","newValue":"4776"},{"stat":"Speed","oldValue":"3.57","newValue":"3.64"}] },
        { "name": "Vanir Queen Freyja", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_fd_14.png", "changes": [{"stat":"AbilityPower","oldValue":"-20","newValue":"30"},{"stat":"AbilityPower+","oldValue":"-30","newValue":"50"},{"stat":"Life","oldValue":"4088","newValue":"4288"}] },
        { "name": "Veren Kaeesu", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_ec_11.png", "changes": [{"stat":"Atk1","oldValue":"1194","newValue":"1394"},{"stat":"Atk1+","oldValue":"1891","newValue":"2291"},{"stat":"Atk2","oldValue":"1194","newValue":"1394"},{"stat":"Atk2+","oldValue":"1891","newValue":"2291"}] },
        { "name": "Xinomas", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_eb_13.png", "changes": [{"stat":"AbilityPower+","oldValue":"30","newValue":"32"},{"stat":"Atk1+","oldValue":"1832","newValue":"2032"},{"stat":"Atk2+","oldValue":"1832","newValue":"2032"},{"stat":"Speed","oldValue":"5.26","newValue":"4.61"}] },
        { "name": "Zagam, Great King of Greed", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_fb_14.png", "changes": [{"stat":"AbilityPower","oldValue":"-15","newValue":"25"},{"stat":"AbilityPower+","oldValue":"-25","newValue":"35"},{"stat":"Speed","oldValue":"4.08","newValue":"4.17"}] }
      ]
    },
    // ========== MARZO 2026 ==========
    {
      title: "Mutantes Rebalanceados - Marzo 2026",
      mutants: [
        { "name": "A027441", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_af_99.png", "changes": [{"stat":"AbilityPower","oldValue":"20","newValue":"20"},{"stat":"AbilityPower+","oldValue":"30","newValue":"40"},{"stat":"Speed","oldValue":"3.23","newValue":"3.23"},{"stat":"Life","oldValue":"2500","newValue":"2950"},{"stat":"Atk1","oldValue":"780","newValue":"780"},{"stat":"Atk1+","oldValue":"1170","newValue":"1370"},{"stat":"Atk2","oldValue":"780","newValue":"780"},{"stat":"Atk2+","oldValue":"1170","newValue":"1370"}] },
        { "name": "Abraham Lincoln", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_af_05.png", "changes": [{"stat":"AbilityPower","oldValue":"15","newValue":"15"},{"stat":"AbilityPower+","oldValue":"25","newValue":"27"},{"stat":"Speed","oldValue":"3.33","newValue":"3.33"},{"stat":"Life","oldValue":"3424","newValue":"3733"},{"stat":"Atk1","oldValue":"1284","newValue":"1518"},{"stat":"Atk1+","oldValue":"1927","newValue":"2227"},{"stat":"Atk2","oldValue":"1284","newValue":"1518"},{"stat":"Atk2+","oldValue":"1927","newValue":"2227"}] },
        { "name": "Alfie", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_ae_07.png", "changes": [{"stat":"AbilityPower","oldValue":"20","newValue":"20"},{"stat":"AbilityPower+","oldValue":"30","newValue":"40"},{"stat":"Speed","oldValue":"3.33","newValue":"3.33"},{"stat":"Life","oldValue":"1722","newValue":"1722"},{"stat":"Atk1","oldValue":"787","newValue":"887"},{"stat":"Atk1+","oldValue":"1183","newValue":"1483"},{"stat":"Atk2","oldValue":"787","newValue":"887"},{"stat":"Atk2+","oldValue":"1183","newValue":"1483"}] },
        { "name": "Azog", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_cf_04.png", "changes": [{"stat":"AbilityPower","oldValue":"15","newValue":"15"},{"stat":"AbilityPower+","oldValue":"25","newValue":"20"},{"stat":"Speed","oldValue":"4.00","newValue":"4.00"},{"stat":"Life","oldValue":"1846","newValue":"1976"},{"stat":"Atk1","oldValue":"600","newValue":"948"},{"stat":"Atk1+","oldValue":"900","newValue":"1468"},{"stat":"Atk2","oldValue":"600","newValue":"948"},{"stat":"Atk2+","oldValue":"900","newValue":"1468"}] },
        { "name": "Bio-Hedgehog", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_ad_06.png", "changes": [{"stat":"AbilityPower","oldValue":"26","newValue":"26"},{"stat":"AbilityPower+","oldValue":"41","newValue":"44"},{"stat":"Speed","oldValue":"3.57","newValue":"3.57"},{"stat":"Life","oldValue":"2286","newValue":"2646"},{"stat":"Atk1","oldValue":"796","newValue":"796"},{"stat":"Atk1+","oldValue":"1188","newValue":"1188"},{"stat":"Atk2","oldValue":"796","newValue":"796"},{"stat":"Atk2+","oldValue":"1188","newValue":"1188"}] },
        { "name": "Black I.C.E.", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_af_14.png", "changes": [{"stat":"AbilityPower","oldValue":"10","newValue":"10"},{"stat":"AbilityPower+","oldValue":"50","newValue":"65"},{"stat":"Speed","oldValue":"10.00","newValue":"10.00"},{"stat":"Life","oldValue":"1351","newValue":"1351"},{"stat":"Atk1","oldValue":"687","newValue":"687"},{"stat":"Atk1+","oldValue":"975","newValue":"875"},{"stat":"Atk2","oldValue":"687","newValue":"687"},{"stat":"Atk2+","oldValue":"975","newValue":"875"}] },
        { "name": "Breakmaster", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_ca_14.png", "changes": [{"stat":"AbilityPower","oldValue":"10","newValue":"10"},{"stat":"AbilityPower+","oldValue":"20","newValue":"20"},{"stat":"Speed","oldValue":"4.76","newValue":"4.55"},{"stat":"Life","oldValue":"2466","newValue":"2166"},{"stat":"Atk1","oldValue":"1233","newValue":"1233"},{"stat":"Atk1+","oldValue":"2024","newValue":"2024"},{"stat":"Atk2","oldValue":"870:AOE","newValue":"870:AOE"},{"stat":"Atk2+","oldValue":"1477:AOE","newValue":"1477:AOE"}] },
        { "name": "Cezanne", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_dc_04.png", "changes": [{"stat":"AbilityPower","oldValue":"20","newValue":"20"},{"stat":"AbilityPower+","oldValue":"40","newValue":"37"},{"stat":"Speed","oldValue":"3.45","newValue":"3.45"},{"stat":"Life","oldValue":"1917","newValue":"1917"},{"stat":"Atk1","oldValue":"700","newValue":"700"},{"stat":"Atk1+","oldValue":"1050","newValue":"1250"},{"stat":"Atk2","oldValue":"700","newValue":"700"},{"stat":"Atk2+","oldValue":"1050","newValue":"1250"}] },
        { "name": "Challengeer", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_ca_05.png", "changes": [{"stat":"AbilityPower","oldValue":"15","newValue":"25"},{"stat":"AbilityPower+","oldValue":"25","newValue":"40"},{"stat":"Speed","oldValue":"6.67","newValue":"6.67"},{"stat":"Life","oldValue":"1297","newValue":"1297"},{"stat":"Atk1","oldValue":"295","newValue":"595"},{"stat":"Atk1+","oldValue":"444","newValue":"844"},{"stat":"Atk2","oldValue":"295","newValue":"595"},{"stat":"Atk2+","oldValue":"444","newValue":"844"}] },
        { "name": "Commander Ender", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_ab_04.png", "changes": [{"stat":"AbilityPower","oldValue":"25","newValue":"25"},{"stat":"AbilityPower+","oldValue":"38","newValue":"38"},{"stat":"Speed","oldValue":"3.85","newValue":"3.85"},{"stat":"Life","oldValue":"1846","newValue":"1846"},{"stat":"Atk1","oldValue":"569","newValue":"869"},{"stat":"Atk1+","oldValue":"854","newValue":"1254"},{"stat":"Atk2","oldValue":"569","newValue":"869"},{"stat":"Atk2+","oldValue":"854","newValue":"1254"}] },
        { "name": "Commodore Le Shark", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_be_04.png", "changes": [{"stat":"AbilityPower","oldValue":"20","newValue":"28"},{"stat":"AbilityPower+","oldValue":"30","newValue":"34"},{"stat":"Speed","oldValue":"3.45","newValue":"3.45"},{"stat":"Life","oldValue":"2195","newValue":"2495"},{"stat":"Atk1","oldValue":"882","newValue":"982"},{"stat":"Atk1+","oldValue":"1323","newValue":"1453"},{"stat":"Atk2","oldValue":"882","newValue":"982"},{"stat":"Atk2+","oldValue":"1323","newValue":"1453"}] },
        { "name": "Crawlorax", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_ed_05.png", "changes": [{"stat":"AbilityPower","oldValue":"20","newValue":"20"},{"stat":"AbilityPower+","oldValue":"30","newValue":"30"},{"stat":"Speed","oldValue":"3.57","newValue":"3.57"},{"stat":"Life","oldValue":"1753","newValue":"1813"},{"stat":"Atk1","oldValue":"622","newValue":"813"},{"stat":"Atk1+","oldValue":"934","newValue":"1379"},{"stat":"Atk2","oldValue":"622","newValue":"813"},{"stat":"Atk2+","oldValue":"934","newValue":"1379"}] },
        { "name": "Deadnosaur", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_db_08.png", "changes": [{"stat":"AbilityPower","oldValue":"20","newValue":"20"},{"stat":"AbilityPower+","oldValue":"40","newValue":"40"},{"stat":"Speed","oldValue":"3.57","newValue":"3.57"},{"stat":"Life","oldValue":"2032","newValue":"2032"},{"stat":"Atk1","oldValue":"615","newValue":"715"},{"stat":"Atk1+","oldValue":"923","newValue":"1423"},{"stat":"Atk2","oldValue":"615","newValue":"715"},{"stat":"Atk2+","oldValue":"923","newValue":"1423"}] },
        { "name": "Draco Mage", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_fd_09.png", "changes": [{"stat":"AbilityPower","oldValue":"15","newValue":"15"},{"stat":"AbilityPower+","oldValue":"25","newValue":"22"},{"stat":"Speed","oldValue":"4.00","newValue":"4.00"},{"stat":"Life","oldValue":"1572","newValue":"2452"},{"stat":"Atk1","oldValue":"579","newValue":"579"},{"stat":"Atk1+","oldValue":"870","newValue":"977"},{"stat":"Atk2","oldValue":"579","newValue":"579"},{"stat":"Atk2+","oldValue":"870","newValue":"977"}] },
        { "name": "Engineer", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_fe_99.png", "changes": [{"stat":"AbilityPower","oldValue":"15","newValue":"15"},{"stat":"AbilityPower+","oldValue":"25","newValue":"28"},{"stat":"Speed","oldValue":"3.85","newValue":"3.85"},{"stat":"Life","oldValue":"2012","newValue":"2012"},{"stat":"Atk1","oldValue":"718","newValue":"718"},{"stat":"Atk1+","oldValue":"1077","newValue":"1447"},{"stat":"Atk2","oldValue":"718","newValue":"718"},{"stat":"Atk2+","oldValue":"1077","newValue":"1447"}] },
        { "name": "Exo Cookie", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_de_05.png", "changes": [{"stat":"AbilityPower","oldValue":"20","newValue":"20"},{"stat":"AbilityPower+","oldValue":"40","newValue":"50"},{"stat":"Speed","oldValue":"3.33","newValue":"3.33"},{"stat":"Life","oldValue":"1915","newValue":"2230"},{"stat":"Atk1","oldValue":"696","newValue":"696"},{"stat":"Atk1+","oldValue":"1046","newValue":"1046"},{"stat":"Atk2","oldValue":"696","newValue":"696"},{"stat":"Atk2+","oldValue":"1046","newValue":"1046"}] },
        { "name": "Genshiryoku", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_de_04.png", "changes": [{"stat":"AbilityPower","oldValue":"20","newValue":"20"},{"stat":"AbilityPower+","oldValue":"40","newValue":"35"},{"stat":"Speed","oldValue":"3.57","newValue":"3.57"},{"stat":"Life","oldValue":"1913","newValue":"1613"},{"stat":"Atk1","oldValue":"622","newValue":"822"},{"stat":"Atk1+","oldValue":"934","newValue":"1534"},{"stat":"Atk2","oldValue":"622","newValue":"822"},{"stat":"Atk2+","oldValue":"934","newValue":"1534"}] },
        { "name": "Grannyvore", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_dc_06.png", "changes": [{"stat":"AbilityPower","oldValue":"25","newValue":"25"},{"stat":"AbilityPower+","oldValue":"38","newValue":"38"},{"stat":"Speed","oldValue":"3.70","newValue":"3.70"},{"stat":"Life","oldValue":"2130","newValue":"2330"},{"stat":"Atk1","oldValue":"633","newValue":"733"},{"stat":"Atk1+","oldValue":"951","newValue":"1151"},{"stat":"Atk2","oldValue":"633","newValue":"733"},{"stat":"Atk2+","oldValue":"951","newValue":"1151"}] },
        { "name": "Hephaestus", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_fc_10.png", "changes": [{"stat":"AbilityPower","oldValue":"15","newValue":"15"},{"stat":"AbilityPower+","oldValue":"25","newValue":"25"},{"stat":"Speed","oldValue":"3.85","newValue":"3.85"},{"stat":"Life","oldValue":"2114","newValue":"2514"},{"stat":"Atk1","oldValue":"698","newValue":"898"},{"stat":"Atk1+","oldValue":"1049","newValue":"1249"},{"stat":"Atk2","oldValue":"698","newValue":"898"},{"stat":"Atk2+","oldValue":"1049","newValue":"1249"}] },
        { "name": "Hercules", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_aa_06.png", "changes": [{"stat":"AbilityPower","oldValue":"20","newValue":"20"},{"stat":"AbilityPower+","oldValue":"30","newValue":"33"},{"stat":"Speed","oldValue":"3.33","newValue":"3.33"},{"stat":"Life","oldValue":"2258","newValue":"2258"},{"stat":"Atk1","oldValue":"845","newValue":"945"},{"stat":"Atk1+","oldValue":"1269","newValue":"1569"},{"stat":"Atk2","oldValue":"485:AOE","newValue":"635:AOE"},{"stat":"Atk2+","oldValue":"729:AOE","newValue":"929:AOE"}] },
        { "name": "Hippopotank", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_ad_10.png", "changes": [{"stat":"AbilityPower","oldValue":"20","newValue":"15"},{"stat":"AbilityPower+","oldValue":"30","newValue":"22"},{"stat":"Speed","oldValue":"3.45","newValue":"3.45"},{"stat":"Life","oldValue":"2477","newValue":"2477"},{"stat":"Atk1","oldValue":"820","newValue":"943"},{"stat":"Atk1+","oldValue":"1229","newValue":"1549"},{"stat":"Atk2","oldValue":"820","newValue":"943"},{"stat":"Atk2+","oldValue":"1229","newValue":"1549"}] },
        { "name": "Kontiki", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_df_04.png", "changes": [{"stat":"AbilityPower","oldValue":"20","newValue":"20"},{"stat":"AbilityPower+","oldValue":"40","newValue":"90"},{"stat":"Speed","oldValue":"3.70","newValue":"3.70"},{"stat":"Life","oldValue":"1887","newValue":"2287"},{"stat":"Atk1","oldValue":"595","newValue":"595"},{"stat":"Atk1+","oldValue":"892","newValue":"892"},{"stat":"Atk2","oldValue":"595","newValue":"595"},{"stat":"Atk2+","oldValue":"892","newValue":"892"}] },
        { "name": "Kraken", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_ef_05.png", "changes": [{"stat":"AbilityPower","oldValue":"25","newValue":"25"},{"stat":"AbilityPower+","oldValue":"38","newValue":"30"},{"stat":"Speed","oldValue":"3.85","newValue":"3.85"},{"stat":"Life","oldValue":"1905","newValue":"1405"},{"stat":"Atk1","oldValue":"587","newValue":"1387"},{"stat":"Atk1+","oldValue":"881","newValue":"2081"},{"stat":"Atk2","oldValue":"587","newValue":"1387"},{"stat":"Atk2+","oldValue":"881","newValue":"2081"}] },
        { "name": "Kung Chow", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_fd_06.png", "changes": [{"stat":"AbilityPower","oldValue":"17","newValue":"17"},{"stat":"AbilityPower+","oldValue":"26","newValue":"24"},{"stat":"Speed","oldValue":"4.17","newValue":"4.17"},{"stat":"Life","oldValue":"1706","newValue":"2706"},{"stat":"Atk1","oldValue":"512","newValue":"512"},{"stat":"Atk1+","oldValue":"769","newValue":"869"},{"stat":"Atk2","oldValue":"512","newValue":"512"},{"stat":"Atk2+","oldValue":"769","newValue":"869"}] },
        { "name": "Majin Zam", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_fe_08.png", "changes": [{"stat":"AbilityPower","oldValue":"15","newValue":"15"},{"stat":"AbilityPower+","oldValue":"25","newValue":"25"},{"stat":"Speed","oldValue":"3.45","newValue":"3.45"},{"stat":"Life","oldValue":"1982","newValue":"1982"},{"stat":"Atk1","oldValue":"640","newValue":"971"},{"stat":"Atk1+","oldValue":"961","newValue":"1561"},{"stat":"Atk2","oldValue":"640","newValue":"971"},{"stat":"Atk2+","oldValue":"961","newValue":"1561"}] },
        { "name": "Omikami", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_fd_08.png", "changes": [{"stat":"AbilityPower","oldValue":"20","newValue":"30"},{"stat":"AbilityPower+","oldValue":"40","newValue":"50"},{"stat":"Speed","oldValue":"3.85","newValue":"3.85"},{"stat":"Life","oldValue":"1857","newValue":"1957"},{"stat":"Atk1","oldValue":"569","newValue":"741"},{"stat":"Atk1+","oldValue":"852","newValue":"1052"},{"stat":"Atk2","oldValue":"569","newValue":"741"},{"stat":"Atk2+","oldValue":"852","newValue":"1052"}] },
        { "name": "Puppetron", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_fe_06.png", "changes": [{"stat":"AbilityPower","oldValue":"13","newValue":"13"},{"stat":"AbilityPower+","oldValue":"22","newValue":"20"},{"stat":"Speed","oldValue":"4.76","newValue":"4.76"},{"stat":"Life","oldValue":"1685","newValue":"1685"},{"stat":"Atk1","oldValue":"440","newValue":"734"},{"stat":"Atk1+","oldValue":"714","newValue":"1128"},{"stat":"Atk2","oldValue":"440","newValue":"734"},{"stat":"Atk2+","oldValue":"714","newValue":"1128"}] },
        { "name": "RA-DK-Bot", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_ca_06.png", "changes": [{"stat":"AbilityPower","oldValue":"15","newValue":"15"},{"stat":"AbilityPower+","oldValue":"25","newValue":"25"},{"stat":"Speed","oldValue":"3.57","newValue":"3.57"},{"stat":"Life","oldValue":"2321","newValue":"2321"},{"stat":"Atk1","oldValue":"630","newValue":"830"},{"stat":"Atk1+","oldValue":"1176","newValue":"1376"},{"stat":"Atk2","oldValue":"630","newValue":"830"},{"stat":"Atk2+","oldValue":"1176","newValue":"1376"}] },
        { "name": "Rocky Botboa", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_ca_07.png", "changes": [{"stat":"AbilityPower","oldValue":"20","newValue":"20"},{"stat":"AbilityPower+","oldValue":"38","newValue":"55"},{"stat":"Speed","oldValue":"3.23","newValue":"3.23"},{"stat":"Life","oldValue":"2431","newValue":"2931"},{"stat":"Atk1","oldValue":"732","newValue":"732"},{"stat":"Atk1+","oldValue":"1100","newValue":"1140"},{"stat":"Atk2","oldValue":"732","newValue":"732"},{"stat":"Atk2+","oldValue":"1100","newValue":"1140"}] },
        { "name": "S-K-Venger", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_ab_10.png", "changes": [{"stat":"AbilityPower","oldValue":"22","newValue":"22"},{"stat":"AbilityPower+","oldValue":"35","newValue":"35"},{"stat":"Speed","oldValue":"3.45","newValue":"3.45"},{"stat":"Life","oldValue":"2125","newValue":"1925"},{"stat":"Atk1","oldValue":"890","newValue":"1141"},{"stat":"Atk1+","oldValue":"1395","newValue":"1795"},{"stat":"Atk2","oldValue":"890","newValue":"1141"},{"stat":"Atk2+","oldValue":"1395","newValue":"1795"}] },
        { "name": "Shadow Shaman", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_fa_05.png", "changes": [{"stat":"AbilityPower","oldValue":"15","newValue":"15"},{"stat":"AbilityPower+","oldValue":"25","newValue":"40"},{"stat":"Speed","oldValue":"5.26","newValue":"5.26"},{"stat":"Life","oldValue":"1464","newValue":"1464"},{"stat":"Atk1","oldValue":"390","newValue":"538"},{"stat":"Atk1+","oldValue":"586","newValue":"884"},{"stat":"Atk2","oldValue":"390","newValue":"538"},{"stat":"Atk2+","oldValue":"586","newValue":"884"}] },
        { "name": "Sir Puggington", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_cd_06.png", "changes": [{"stat":"AbilityPower","oldValue":"20","newValue":"20"},{"stat":"AbilityPower+","oldValue":"37","newValue":"35"},{"stat":"Speed","oldValue":"3.45","newValue":"3.45"},{"stat":"Life","oldValue":"2868","newValue":"3268"},{"stat":"Atk1","oldValue":"699","newValue":"699"},{"stat":"Atk1+","oldValue":"1049","newValue":"1049"},{"stat":"Atk2","oldValue":"699","newValue":"699"},{"stat":"Atk2+","oldValue":"1049","newValue":"1049"}] },
        { "name": "Space Hunter", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_ec_05.png", "changes": [{"stat":"AbilityPower","oldValue":"20","newValue":"20"},{"stat":"AbilityPower+","oldValue":"32","newValue":"27"},{"stat":"Speed","oldValue":"4.35","newValue":"4.35"},{"stat":"Life","oldValue":"1602","newValue":"1802"},{"stat":"Atk1","oldValue":"491","newValue":"691"},{"stat":"Atk1+","oldValue":"737","newValue":"1037"},{"stat":"Atk2","oldValue":"491","newValue":"691"},{"stat":"Atk2+","oldValue":"737","newValue":"1037"}] },
        { "name": "Space Pilgrim", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_ea_13.png", "changes": [{"stat":"AbilityPower","oldValue":"15","newValue":"15"},{"stat":"AbilityPower+","oldValue":"35","newValue":"32"},{"stat":"Speed","oldValue":"6.25","newValue":"5.88"},{"stat":"Life","oldValue":"1972","newValue":"1872"},{"stat":"Atk1","oldValue":"761","newValue":"761"},{"stat":"Atk1+","oldValue":"1244","newValue":"1244"},{"stat":"Atk2","oldValue":"761","newValue":"761"},{"stat":"Atk2+","oldValue":"984:AOE","newValue":"984:AOE"}] },
        { "name": "Starscream", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_ec_07.png", "changes": [{"stat":"AbilityPower","oldValue":"20","newValue":"20"},{"stat":"AbilityPower+","oldValue":"30","newValue":"30"},{"stat":"Speed","oldValue":"4.00","newValue":"4.00"},{"stat":"Life","oldValue":"1622","newValue":"1622"},{"stat":"Atk1","oldValue":"580","newValue":"751"},{"stat":"Atk1+","oldValue":"870","newValue":"1374"},{"stat":"Atk2","oldValue":"580","newValue":"751"},{"stat":"Atk2+","oldValue":"870","newValue":"1374"}] },
        { "name": "The Chimera", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_df_07.png", "changes": [{"stat":"AbilityPower","oldValue":"15","newValue":"15"},{"stat":"AbilityPower+","oldValue":"25","newValue":"25"},{"stat":"Speed","oldValue":"3.70","newValue":"3.70"},{"stat":"Life","oldValue":"1872","newValue":"1832"},{"stat":"Atk1","oldValue":"587","newValue":"887"},{"stat":"Atk1+","oldValue":"1326","newValue":"1626"},{"stat":"Atk2","oldValue":"587","newValue":"887"},{"stat":"Atk2+","oldValue":"1326","newValue":"1626"}] },
        { "name": "The Keymaster", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_cf_09.png", "changes": [{"stat":"AbilityPower","oldValue":"15","newValue":"30"},{"stat":"AbilityPower+","oldValue":"25","newValue":"50"},{"stat":"Speed","oldValue":"3.57","newValue":"3.57"},{"stat":"Life","oldValue":"1860","newValue":"1860"},{"stat":"Atk1","oldValue":"698","newValue":"898"},{"stat":"Atk1+","oldValue":"1040","newValue":"1440"},{"stat":"Atk2","oldValue":"698","newValue":"898"},{"stat":"Atk2+","oldValue":"1040","newValue":"1440"}] },
        { "name": "Thrann", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_bc_08.png", "changes": [{"stat":"AbilityPower","oldValue":"22","newValue":"22"},{"stat":"AbilityPower+","oldValue":"35","newValue":"25"},{"stat":"Speed","oldValue":"4.00","newValue":"4.00"},{"stat":"Life","oldValue":"1482","newValue":"1482"},{"stat":"Atk1","oldValue":"539","newValue":"862"},{"stat":"Atk1+","oldValue":"962","newValue":"1482"},{"stat":"Atk2","oldValue":"539","newValue":"862"},{"stat":"Atk2+","oldValue":"962","newValue":"1482"}] },
        { "name": "Tricera Tank", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_da_06.png", "changes": [{"stat":"AbilityPower","oldValue":"20","newValue":"20"},{"stat":"AbilityPower+","oldValue":"30","newValue":"40"},{"stat":"Speed","oldValue":"3.23","newValue":"3.23"},{"stat":"Life","oldValue":"1973","newValue":"1973"},{"stat":"Atk1","oldValue":"758","newValue":"758"},{"stat":"Atk1+","oldValue":"1137","newValue":"1237"},{"stat":"Atk2","oldValue":"758","newValue":"758"},{"stat":"Atk2+","oldValue":"1137","newValue":"1237"}] },
        { "name": "Undead Soldier", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_eb_05.png", "changes": [{"stat":"AbilityPower","oldValue":"20","newValue":"20"},{"stat":"AbilityPower+","oldValue":"30","newValue":"30"},{"stat":"Speed","oldValue":"3.70","newValue":"3.70"},{"stat":"Life","oldValue":"1860","newValue":"1860"},{"stat":"Atk1","oldValue":"641","newValue":"871"},{"stat":"Atk1+","oldValue":"961","newValue":"1246"},{"stat":"Atk2","oldValue":"641","newValue":"871"},{"stat":"Atk2+","oldValue":"961","newValue":"1246"}] },
        { "name": "Wicked Witch", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_fb_04.png", "changes": [{"stat":"AbilityPower","oldValue":"15","newValue":"15"},{"stat":"AbilityPower+","oldValue":"25","newValue":"22"},{"stat":"Speed","oldValue":"4.17","newValue":"4.17"},{"stat":"Life","oldValue":"1763","newValue":"1763"},{"stat":"Atk1","oldValue":"556","newValue":"756"},{"stat":"Atk1+","oldValue":"834","newValue":"1234"},{"stat":"Atk2","oldValue":"556","newValue":"756"},{"stat":"Atk2+","oldValue":"834","newValue":"1234"}] },
        { "name": "Wrath", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_cb_08.png", "changes": [{"stat":"AbilityPower","oldValue":"22","newValue":"22"},{"stat":"AbilityPower+","oldValue":"35","newValue":"35"},{"stat":"Speed","oldValue":"3.70","newValue":"3.70"},{"stat":"Life","oldValue":"1463","newValue":"1463"},{"stat":"Atk1","oldValue":"1020","newValue":"1120"},{"stat":"Atk1+","oldValue":"1530","newValue":"1690"},{"stat":"Atk2","oldValue":"1020","newValue":"1120"},{"stat":"Atk2+","oldValue":"1530","newValue":"1690"}] },
        { "name": "Wynn", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_cf_08.png", "changes": [{"stat":"AbilityPower","oldValue":"27","newValue":"27"},{"stat":"AbilityPower+","oldValue":"37","newValue":"41"},{"stat":"Speed","oldValue":"3.33","newValue":"3.33"},{"stat":"Life","oldValue":"2195","newValue":"2095"},{"stat":"Atk1","oldValue":"723","newValue":"723"},{"stat":"Atk1+","oldValue":"1085","newValue":"1285"},{"stat":"Atk2","oldValue":"723","newValue":"723"},{"stat":"Atk2+","oldValue":"1085","newValue":"1285"}] },
        { "name": "Xeleroth", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_fe_09.png", "changes": [{"stat":"AbilityPower","oldValue":"15","newValue":"15"},{"stat":"AbilityPower+","oldValue":"25","newValue":"20"},{"stat":"Speed","oldValue":"3.45","newValue":"3.45"},{"stat":"Life","oldValue":"2145","newValue":"2345"},{"stat":"Atk1","oldValue":"769","newValue":"949"},{"stat":"Atk1+","oldValue":"1153","newValue":"1418"},{"stat":"Atk2","oldValue":"769","newValue":"949"},{"stat":"Atk2+","oldValue":"1153","newValue":"1418"}] },
        { "name": "Z-0", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_ba_06.png", "changes": [{"stat":"AbilityPower","oldValue":"16","newValue":"16"},{"stat":"AbilityPower+","oldValue":"27","newValue":"27"},{"stat":"Speed","oldValue":"3.85","newValue":"3.85"},{"stat":"Life","oldValue":"1980","newValue":"2041"},{"stat":"Atk1","oldValue":"747","newValue":"947"},{"stat":"Atk1+","oldValue":"1122","newValue":"1322"},{"stat":"Atk2","oldValue":"747","newValue":"947"},{"stat":"Atk2+","oldValue":"1122","newValue":"1322"}] }
      ]
    },
    // ========== NOVIEMBRE 2025 ==========
    {
      title: "Mutantes Rebalanceados - Noviembre 2025",
      mutants: [
        { "name": "Goliath", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_aa_02.png", "changes": [{"stat":"AbilityPower","oldValue":"20","newValue":"20"},{"stat":"AbilityPower+","oldValue":"40","newValue":"40"},{"stat":"Speed","oldValue":"3.85","newValue":"3.85"},{"stat":"Life","oldValue":"3676","newValue":"3676"},{"stat":"Atk1","oldValue":"1199","newValue":"1199"},{"stat":"Atk1+","oldValue":"1799","newValue":"1999"},{"stat":"Atk2","oldValue":"689","newValue":"689:AOE"},{"stat":"Atk2+","oldValue":"1034","newValue":"1334:AOE"}] },
        { "name": "Mr Marvelous", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_ef_02.png", "changes": [{"stat":"AbilityPower","oldValue":"30","newValue":"30"},{"stat":"AbilityPower+","oldValue":"50","newValue":"60"},{"stat":"Speed","oldValue":"5.26","newValue":"5.00"},{"stat":"Life","oldValue":"2986","newValue":"2986"},{"stat":"Atk1","oldValue":"438","newValue":"438"},{"stat":"Atk1+","oldValue":"576","newValue":"616"},{"stat":"Atk2","oldValue":"438","newValue":"438"},{"stat":"Atk2+","oldValue":"576","newValue":"636"}] },
        { "name": "Gargantus", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_dc_03.png", "changes": [{"stat":"AbilityPower","oldValue":"20","newValue":"50"},{"stat":"AbilityPower+","oldValue":"50","newValue":"75"},{"stat":"Speed","oldValue":"4.76","newValue":"4.76"},{"stat":"Life","oldValue":"1914","newValue":"1914"},{"stat":"Atk1","oldValue":"501","newValue":"501"},{"stat":"Atk1+","oldValue":"752","newValue":"802"},{"stat":"Atk2","oldValue":"501","newValue":"501"},{"stat":"Atk2+","oldValue":"752","newValue":"802"}] },
        { "name": "Oriax", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_fc_03.png", "changes": [{"stat":"AbilityPower","oldValue":"15","newValue":"20"},{"stat":"AbilityPower+","oldValue":"25","newValue":"30"},{"stat":"Speed","oldValue":"3.57","newValue":"3.57"},{"stat":"Life","oldValue":"3344","newValue":"3944"},{"stat":"Atk1","oldValue":"1187","newValue":"1187"},{"stat":"Atk1+","oldValue":"1780","newValue":"1780"},{"stat":"Atk2","oldValue":"1187","newValue":"1187"},{"stat":"Atk2+","oldValue":"1780","newValue":"1780"}] },
        { "name": "Ivory Hanzo", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_fd_03.png", "changes": [{"stat":"AbilityPower","oldValue":"15","newValue":"20"},{"stat":"AbilityPower+","oldValue":"25","newValue":"30"},{"stat":"Speed","oldValue":"3.70","newValue":"3.70"},{"stat":"Life","oldValue":"1830","newValue":"1924"},{"stat":"Atk1","oldValue":"630","newValue":"879"},{"stat":"Atk1+","oldValue":"945","newValue":"1545"},{"stat":"Atk2","oldValue":"630","newValue":"879"},{"stat":"Atk2+","oldValue":"945","newValue":"1545"}] },
        { "name": "Galactic Emperor", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_bf_04.png", "changes": [{"stat":"AbilityPower","oldValue":"30","newValue":"55"},{"stat":"AbilityPower+","oldValue":"55","newValue":"80"},{"stat":"Speed","oldValue":"6.25","newValue":"6.25"},{"stat":"Life","oldValue":"1694","newValue":"2094"},{"stat":"Atk1","oldValue":"361","newValue":"361"},{"stat":"Atk1+","oldValue":"543","newValue":"543"},{"stat":"Atk2","oldValue":"361","newValue":"361"},{"stat":"Atk2+","oldValue":"543","newValue":"543"}] },
        { "name": "Rakk 'n' Ruin", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_ed_04.png", "changes": [{"stat":"AbilityPower","oldValue":"20","newValue":"25"},{"stat":"AbilityPower+","oldValue":"40","newValue":"40"},{"stat":"Speed","oldValue":"12.50","newValue":"12.50"},{"stat":"Life","oldValue":"1669","newValue":"1669"},{"stat":"Atk1","oldValue":"255","newValue":"335"},{"stat":"Atk1+","oldValue":"415","newValue":"515"},{"stat":"Atk2","oldValue":"255","newValue":"335"},{"stat":"Atk2+","oldValue":"415","newValue":"515"}] },
        { "name": "Neo-Urban XIII", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_ab_05.png", "changes": [{"stat":"AbilityPower","oldValue":"12","newValue":"12"},{"stat":"AbilityPower+","oldValue":"33","newValue":"33"},{"stat":"Speed","oldValue":"3.33","newValue":"3.33"},{"stat":"Life","oldValue":"2452","newValue":"2552"},{"stat":"Atk1","oldValue":"558","newValue":"558"},{"stat":"Atk1+","oldValue":"1384","newValue":"1384"},{"stat":"Atk2","oldValue":"558","newValue":"558"},{"stat":"Atk2+","oldValue":"1384","newValue":"1384"}] },
        { "name": "Drudge Zombie", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_b_05.png", "changes": [{"stat":"AbilityPower","oldValue":"35","newValue":"35"},{"stat":"AbilityPower+","oldValue":"50","newValue":"60"},{"stat":"Speed","oldValue":"7.14","newValue":"6.67"},{"stat":"Life","oldValue":"2030","newValue":"2230"},{"stat":"Atk1","oldValue":"507","newValue":"507"},{"stat":"Atk1+","oldValue":"915","newValue":"915"},{"stat":"Atk2","oldValue":"507","newValue":"507"},{"stat":"Atk2+","oldValue":"915","newValue":"915"}] },
        { "name": "Barbarian", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_c_05.png", "changes": [{"stat":"AbilityPower","oldValue":"20","newValue":"20"},{"stat":"AbilityPower+","oldValue":"40","newValue":"40"},{"stat":"Speed","oldValue":"4.26","newValue":"4.26"},{"stat":"Life","oldValue":"2382","newValue":"2382"},{"stat":"Atk1","oldValue":"877","newValue":"877"},{"stat":"Atk1+","oldValue":"1315","newValue":"1405"},{"stat":"Atk2","oldValue":"877","newValue":"877"},{"stat":"Atk2+","oldValue":"1315","newValue":"1405"}] },
        { "name": "Hog the Ripper", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_cd_05.png", "changes": [{"stat":"AbilityPower","oldValue":"15","newValue":"13"},{"stat":"AbilityPower+","oldValue":"24","newValue":"20"},{"stat":"Speed","oldValue":"3.23","newValue":"3.23"},{"stat":"Life","oldValue":"4480","newValue":"4580"},{"stat":"Atk1","oldValue":"1633","newValue":"1633"},{"stat":"Atk1+","oldValue":"2449","newValue":"2549"},{"stat":"Atk2","oldValue":"1633","newValue":"1633"},{"stat":"Atk2+","oldValue":"2449","newValue":"2549"}] },
        { "name": "Sun-Duke", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_ce_05.png", "changes": [{"stat":"AbilityPower","oldValue":"20","newValue":"20"},{"stat":"AbilityPower+","oldValue":"30","newValue":"30"},{"stat":"Speed","oldValue":"6.33","newValue":"6.25"},{"stat":"Life","oldValue":"1405","newValue":"1405"},{"stat":"Atk1","oldValue":"331","newValue":"531"},{"stat":"Atk1+","oldValue":"496","newValue":"996"},{"stat":"Atk2","oldValue":"331","newValue":"531"},{"stat":"Atk2+","oldValue":"496","newValue":"996"}] },
        { "name": "Eva\u00b4s Replication", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_af_06.png", "changes": [{"stat":"AbilityPower","oldValue":"20","newValue":"20"},{"stat":"AbilityPower+","oldValue":"35","newValue":"35"},{"stat":"Speed","oldValue":"9.09","newValue":"9.09"},{"stat":"Life","oldValue":"2633","newValue":"2633"},{"stat":"Atk1","oldValue":"439","newValue":"439"},{"stat":"Atk1+","oldValue":"658","newValue":"738"},{"stat":"Atk2","oldValue":"439","newValue":"439"},{"stat":"Atk2+","oldValue":"658","newValue":"738"}] },
        { "name": "Scarlett", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_cb_06.png", "changes": [{"stat":"AbilityPower","oldValue":"15","newValue":"25"},{"stat":"AbilityPower+","oldValue":"33","newValue":"45"},{"stat":"Speed","oldValue":"5.56","newValue":"5.56"},{"stat":"Life","oldValue":"2813","newValue":"2813"},{"stat":"Atk1","oldValue":"720","newValue":"720"},{"stat":"Atk1+","oldValue":"1382","newValue":"1432"},{"stat":"Atk2","oldValue":"720","newValue":"720"},{"stat":"Atk2+","oldValue":"1382","newValue":"1432"}] },
        { "name": "Crusher", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_ab_07.png", "changes": [{"stat":"AbilityPower","oldValue":"30","newValue":"30"},{"stat":"AbilityPower+","oldValue":"45","newValue":"45"},{"stat":"Speed","oldValue":"4.55","newValue":"4.00"},{"stat":"Life","oldValue":"3210","newValue":"3210"},{"stat":"Atk1","oldValue":"979","newValue":"979"},{"stat":"Atk1+","oldValue":"1472","newValue":"1872"},{"stat":"Atk2","oldValue":"979","newValue":"979"},{"stat":"Atk2+","oldValue":"1472","newValue":"1872"}] },
        { "name": "Garlog", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_eb_06.png", "changes": [{"stat":"AbilityPower","oldValue":"22","newValue":"30"},{"stat":"AbilityPower+","oldValue":"32","newValue":"45"},{"stat":"Speed","oldValue":"4.44","newValue":"4.44"},{"stat":"Life","oldValue":"1963","newValue":"1963"},{"stat":"Atk1","oldValue":"791","newValue":"861"},{"stat":"Atk1+","oldValue":"1286","newValue":"1316"},{"stat":"Atk2","oldValue":"791","newValue":"861"},{"stat":"Atk2+","oldValue":"1286","newValue":"1316"}] },
        { "name": "Zeus", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_ec_06.png", "changes": [{"stat":"AbilityPower","oldValue":"10","newValue":"25"},{"stat":"AbilityPower+","oldValue":"35","newValue":"40"},{"stat":"Speed","oldValue":"11.11","newValue":"11.11"},{"stat":"Life","oldValue":"940","newValue":"940"},{"stat":"Atk1","oldValue":"571","newValue":"471"},{"stat":"Atk1+","oldValue":"809","newValue":"639"},{"stat":"Atk2","oldValue":"571","newValue":"471"},{"stat":"Atk2+","oldValue":"809","newValue":"639"}] },
        { "name": "Lily", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_fa_06.png", "changes": [{"stat":"AbilityPower","oldValue":"15","newValue":"20"},{"stat":"AbilityPower+","oldValue":"25","newValue":"45"},{"stat":"Speed","oldValue":"5.88","newValue":"5.88"},{"stat":"Life","oldValue":"2247","newValue":"2247"},{"stat":"Atk1","oldValue":"536","newValue":"536"},{"stat":"Atk1+","oldValue":"804","newValue":"804"},{"stat":"Atk2","oldValue":"536","newValue":"536"},{"stat":"Atk2+","oldValue":"804","newValue":"804"}] },
        { "name": "Spartac", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_cc_07.png", "changes": [{"stat":"AbilityPower","oldValue":"20","newValue":"20"},{"stat":"AbilityPower+","oldValue":"30","newValue":"35"},{"stat":"Speed","oldValue":"3.45","newValue":"3.33"},{"stat":"Life","oldValue":"4630","newValue":"4630"},{"stat":"Atk1","oldValue":"1800","newValue":"1800"},{"stat":"Atk1+","oldValue":"2700","newValue":"2700"},{"stat":"Atk2","oldValue":"899:AOE","newValue":"899:AOE"},{"stat":"Atk2+","oldValue":"1261:AOE","newValue":"1261:AOE"}] },
        { "name": "Robo Fuerte", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_ac_07.png", "changes": [{"stat":"AbilityPower","oldValue":"30","newValue":"30"},{"stat":"AbilityPower+","oldValue":"50","newValue":"50"},{"stat":"Speed","oldValue":"4.00","newValue":"4.00"},{"stat":"Life","oldValue":"1881","newValue":"2181"},{"stat":"Atk1","oldValue":"856","newValue":"856"},{"stat":"Atk1+","oldValue":"1284","newValue":"1284"},{"stat":"Atk2","oldValue":"856","newValue":"856"},{"stat":"Atk2+","oldValue":"1284","newValue":"1284"}] },
        { "name": "Noren", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_dc_07.png", "changes": [{"stat":"AbilityPower","oldValue":"20","newValue":"20"},{"stat":"AbilityPower+","oldValue":"30","newValue":"30"},{"stat":"Speed","oldValue":"3.70","newValue":"3.85"},{"stat":"Life","oldValue":"4038","newValue":"4338"},{"stat":"Atk1","oldValue":"1460","newValue":"1460"},{"stat":"Atk1+","oldValue":"2194","newValue":"2194"},{"stat":"Atk2","oldValue":"1460","newValue":"1460"},{"stat":"Atk2+","oldValue":"2194","newValue":"2194"}] },
        { "name": "The Primal", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_bd_07.png", "changes": [{"stat":"AbilityPower","oldValue":"30","newValue":"30"},{"stat":"AbilityPower+","oldValue":"55","newValue":"55"},{"stat":"Speed","oldValue":"5.56","newValue":"5.56"},{"stat":"Life","oldValue":"2622","newValue":"2622"},{"stat":"Atk1","oldValue":"516","newValue":"516"},{"stat":"Atk1+","oldValue":"774","newValue":"974"},{"stat":"Atk2","oldValue":"516","newValue":"516"},{"stat":"Atk2+","oldValue":"774","newValue":"974"}] },
        { "name": "Geomega", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_ff_07.png", "changes": [{"stat":"AbilityPower","oldValue":"15","newValue":"15"},{"stat":"AbilityPower+","oldValue":"20","newValue":"22"},{"stat":"Speed","oldValue":"3.45","newValue":"3.45"},{"stat":"Life","oldValue":"4093","newValue":"4093"},{"stat":"Atk1","oldValue":"1493","newValue":"1493"},{"stat":"Atk1+","oldValue":"2439","newValue":"2439"},{"stat":"Atk2","oldValue":"746:AOE","newValue":"746:AOE"},{"stat":"Atk2+","oldValue":"1319:AOE","newValue":"1719:AOE"}] },
        { "name": "Dr. Nucleus", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_eb_08.png", "changes": [{"stat":"AbilityPower","oldValue":"20","newValue":"20"},{"stat":"AbilityPower+","oldValue":"30","newValue":"30"},{"stat":"Speed","oldValue":"3.85","newValue":"3.85"},{"stat":"Life","oldValue":"4234","newValue":"4234"},{"stat":"Atk1","oldValue":"1418","newValue":"1518"},{"stat":"Atk1+","oldValue":"2127","newValue":"2227"},{"stat":"Atk2","oldValue":"1418","newValue":"1518"},{"stat":"Atk2+","oldValue":"2127","newValue":"2227"}] },
        { "name": "Akai-Bot", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_ae_10.png", "changes": [{"stat":"AbilityPower","oldValue":"20","newValue":"30"},{"stat":"AbilityPower+","oldValue":"30","newValue":"45"},{"stat":"Speed","oldValue":"5.00","newValue":"5.00"},{"stat":"Life","oldValue":"4200","newValue":"4200"},{"stat":"Atk1","oldValue":"1041","newValue":"1041"},{"stat":"Atk1+","oldValue":"1562","newValue":"1562"},{"stat":"Atk2","oldValue":"1041","newValue":"1041"},{"stat":"Atk2+","oldValue":"1562","newValue":"1562"}] },
        { "name": "Captain Achabe", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_ce_10.png", "changes": [{"stat":"AbilityPower","oldValue":"15","newValue":"13"},{"stat":"AbilityPower+","oldValue":"25","newValue":"20"},{"stat":"Speed","oldValue":"7.41","newValue":"7.69"},{"stat":"Life","oldValue":"3950","newValue":"3550"},{"stat":"Atk1","oldValue":"567","newValue":"667"},{"stat":"Atk1+","oldValue":"930","newValue":"1130"},{"stat":"Atk2","oldValue":"567","newValue":"667"},{"stat":"Atk2+","oldValue":"930","newValue":"1130"}] },
        { "name": "Space Surfer", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_ea_10.png", "changes": [{"stat":"AbilityPower","oldValue":"20","newValue":"13"},{"stat":"AbilityPower+","oldValue":"30","newValue":"20"},{"stat":"Speed","oldValue":"4.00","newValue":"3.85"},{"stat":"Life","oldValue":"4255","newValue":"4455"},{"stat":"Atk1","oldValue":"1538","newValue":"1638"},{"stat":"Atk1+","oldValue":"2307","newValue":"2407"},{"stat":"Atk2","oldValue":"1538","newValue":"1638"},{"stat":"Atk2+","oldValue":"2307","newValue":"2407"}] },
        { "name": "Heimdall", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_af_11.png", "changes": [{"stat":"AbilityPower","oldValue":"15","newValue":"16"},{"stat":"AbilityPower+","oldValue":"25","newValue":"28"},{"stat":"Speed","oldValue":"7.69","newValue":"7.69"},{"stat":"Life","oldValue":"3000","newValue":"3321"},{"stat":"Atk1","oldValue":"900","newValue":"900"},{"stat":"Atk1+","oldValue":"1380","newValue":"1380"},{"stat":"Atk2","oldValue":"900","newValue":"900"},{"stat":"Atk2+","oldValue":"1380","newValue":"1380"}] },
        { "name": "The Forgotten One", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_bb_11.png", "changes": [{"stat":"AbilityPower","oldValue":"35","newValue":"38"},{"stat":"AbilityPower+","oldValue":"53","newValue":"55"},{"stat":"Speed","oldValue":"4.76","newValue":"4.55"},{"stat":"Life","oldValue":"5480","newValue":"5480"},{"stat":"Atk1","oldValue":"996","newValue":"1036"},{"stat":"Atk1+","oldValue":"1494","newValue":"1544"},{"stat":"Atk2","oldValue":"573:AOE","newValue":"613:AOE"},{"stat":"Atk2+","oldValue":"859:AOE","newValue":"959:AOE"}] },
        { "name": "Dreadnought", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_ea_11.png", "changes": [{"stat":"AbilityPower","oldValue":"25","newValue":"25"},{"stat":"AbilityPower+","oldValue":"50","newValue":"50"},{"stat":"Speed","oldValue":"3.64","newValue":"3.64"},{"stat":"Life","oldValue":"4488","newValue":"4488"},{"stat":"Atk1","oldValue":"1311","newValue":"1511"},{"stat":"Atk1+","oldValue":"1966","newValue":"2266"},{"stat":"Atk2","oldValue":"1311","newValue":"1511"},{"stat":"Atk2+","oldValue":"1966","newValue":"2266"}] },
        { "name": "Viper", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_ac_06.png", "changes": [{"stat":"AbilityPower","oldValue":"20","newValue":"20"},{"stat":"AbilityPower+","oldValue":"52","newValue":"52"},{"stat":"Speed","oldValue":"5.26","newValue":"5.88"},{"stat":"Life","oldValue":"1623","newValue":"1788"},{"stat":"Atk1","oldValue":"631","newValue":"631"},{"stat":"Atk1+","oldValue":"946","newValue":"946"},{"stat":"Atk2","oldValue":"631","newValue":"631"},{"stat":"Atk2+","oldValue":"946","newValue":"946"}] },
        { "name": "Bounda", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_af_07.png", "changes": [{"stat":"AbilityPower","oldValue":"25","newValue":"25"},{"stat":"AbilityPower+","oldValue":"35","newValue":"35"},{"stat":"Speed","oldValue":"3.33","newValue":"3.33"},{"stat":"Life","oldValue":"1755","newValue":"2155"},{"stat":"Atk1","oldValue":"824","newValue":"824"},{"stat":"Atk1+","oldValue":"1237","newValue":"1237"},{"stat":"Atk2","oldValue":"824","newValue":"824"},{"stat":"Atk2+","oldValue":"1237","newValue":"1237"}] },
        { "name": "The Skeleton King", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_cb_07.png", "changes": [{"stat":"AbilityPower","oldValue":"25","newValue":"30"},{"stat":"AbilityPower+","oldValue":"45","newValue":"50"},{"stat":"Speed","oldValue":"6.25","newValue":"6.25"},{"stat":"Life","oldValue":"1670","newValue":"1670"},{"stat":"Atk1","oldValue":"501","newValue":"621"},{"stat":"Atk1+","oldValue":"752","newValue":"1052"},{"stat":"Atk2","oldValue":"501","newValue":"621"},{"stat":"Atk2+","oldValue":"752","newValue":"1052"}] },
        { "name": "Aran", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_ce_07.png", "changes": [{"stat":"AbilityPower","oldValue":"20","newValue":"20"},{"stat":"AbilityPower+","oldValue":"30","newValue":"30"},{"stat":"Speed","oldValue":"3.85","newValue":"4.35"},{"stat":"Life","oldValue":"1423","newValue":"1423"},{"stat":"Atk1","oldValue":"595","newValue":"895"},{"stat":"Atk1+","oldValue":"894","newValue":"1494"},{"stat":"Atk2","oldValue":"595","newValue":"895"},{"stat":"Atk2+","oldValue":"894","newValue":"1494"}] },
        { "name": "Lord Dragon", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_db_07.png", "changes": [{"stat":"AbilityPower","oldValue":"25","newValue":"25"},{"stat":"AbilityPower+","oldValue":"85","newValue":"85"},{"stat":"Speed","oldValue":"10.00","newValue":"10.53"},{"stat":"Life","oldValue":"995","newValue":"915"},{"stat":"Atk1","oldValue":"207","newValue":"207"},{"stat":"Atk1+","oldValue":"303","newValue":"303"},{"stat":"Atk2","oldValue":"207","newValue":"207"},{"stat":"Atk2+","oldValue":"303","newValue":"303"}] },
        { "name": "Sound Killah", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_da_09.png", "changes": [{"stat":"AbilityPower","oldValue":"20","newValue":"20"},{"stat":"AbilityPower+","oldValue":"30","newValue":"30"},{"stat":"Speed","oldValue":"3.45","newValue":"3.45"},{"stat":"Life","oldValue":"2136","newValue":"2136"},{"stat":"Atk1","oldValue":"1073","newValue":"1358"},{"stat":"Atk1+","oldValue":"1609","newValue":"2009"},{"stat":"Atk2","oldValue":"1073","newValue":"1358"},{"stat":"Atk2+","oldValue":"1609","newValue":"2009"}] },
        { "name": "Phoenix", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_fd_07.png", "changes": [{"stat":"AbilityPower","oldValue":"25","newValue":"25"},{"stat":"AbilityPower+","oldValue":"45","newValue":"45"},{"stat":"Speed","oldValue":"3.57","newValue":"4.00"},{"stat":"Life","oldValue":"1616","newValue":"2016"},{"stat":"Atk1","oldValue":"5","newValue":"5"},{"stat":"Atk1+","oldValue":"1355","newValue":"1355"},{"stat":"Atk2","oldValue":"5","newValue":"5"},{"stat":"Atk2+","oldValue":"1355","newValue":"1355"}] },
        { "name": "Andromeda", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_ae_08.png", "changes": [{"stat":"AbilityPower","oldValue":"20","newValue":"50"},{"stat":"AbilityPower+","oldValue":"30","newValue":"80"},{"stat":"Speed","oldValue":"7.14","newValue":"7.14"},{"stat":"Life","oldValue":"1065","newValue":"1065"},{"stat":"Atk1","oldValue":"307","newValue":"455"},{"stat":"Atk1+","oldValue":"461","newValue":"661"},{"stat":"Atk2","oldValue":"307","newValue":"455"},{"stat":"Atk2+","oldValue":"461","newValue":"661"}] },
        { "name": "Asaylan", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_da_08.png", "changes": [{"stat":"AbilityPower","oldValue":"30","newValue":"50"},{"stat":"AbilityPower+","oldValue":"60","newValue":"100"},{"stat":"Speed","oldValue":"4.76","newValue":"5.00"},{"stat":"Life","oldValue":"1366","newValue":"1266"},{"stat":"Atk1","oldValue":"805","newValue":"805"},{"stat":"Atk1+","oldValue":"1206","newValue":"1206"},{"stat":"Atk2","oldValue":"805","newValue":"805"},{"stat":"Atk2+","oldValue":"1206","newValue":"1206"}] },
        { "name": "Chantecler", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_df_08.png", "changes": [{"stat":"AbilityPower","oldValue":"20","newValue":"20"},{"stat":"AbilityPower+","oldValue":"40","newValue":"40"},{"stat":"Speed","oldValue":"3.57","newValue":"3.57"},{"stat":"Life","oldValue":"1682","newValue":"1982"},{"stat":"Atk1","oldValue":"887","newValue":"987"},{"stat":"Atk1+","oldValue":"1331","newValue":"1381"},{"stat":"Atk2","oldValue":"887","newValue":"987"},{"stat":"Atk2+","oldValue":"1331","newValue":"1381"}] },
        { "name": "Spectre", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_ec_08.png", "changes": [{"stat":"AbilityPower","oldValue":"22","newValue":"22"},{"stat":"AbilityPower+","oldValue":"33","newValue":"33"},{"stat":"Speed","oldValue":"8.33","newValue":"8.33"},{"stat":"Life","oldValue":"987","newValue":"687"},{"stat":"Atk1","oldValue":"233","newValue":"533"},{"stat":"Atk1+","oldValue":"352","newValue":"852"},{"stat":"Atk2","oldValue":"233","newValue":"533"},{"stat":"Atk2+","oldValue":"352","newValue":"852"}] },
        { "name": "Steam Warlord", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_af_09.png", "changes": [{"stat":"AbilityPower","oldValue":"20","newValue":"30"},{"stat":"AbilityPower+","oldValue":"35","newValue":"45"},{"stat":"Speed","oldValue":"4.44","newValue":"4.44"},{"stat":"Life","oldValue":"2215","newValue":"2415"},{"stat":"Atk1","oldValue":"546","newValue":"606"},{"stat":"Atk1+","oldValue":"806","newValue":"906"},{"stat":"Atk2","oldValue":"546","newValue":"606"},{"stat":"Atk2+","oldValue":"806","newValue":"906"}] },
        { "name": "Queen Sylvidra", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_eb_09.png", "changes": [{"stat":"AbilityPower","oldValue":"40","newValue":"40"},{"stat":"AbilityPower+","oldValue":"60","newValue":"60"},{"stat":"Speed","oldValue":"3.57","newValue":"3.57"},{"stat":"Life","oldValue":"1702","newValue":"2302"},{"stat":"Atk1","oldValue":"699","newValue":"699"},{"stat":"Atk1+","oldValue":"1048","newValue":"1148"},{"stat":"Atk2","oldValue":"699","newValue":"699"},{"stat":"Atk2+","oldValue":"1048","newValue":"1148"}] },
        { "name": "Sergeant Dusk", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_ac_10.png", "changes": [{"stat":"AbilityPower","oldValue":"15","newValue":"25"},{"stat":"AbilityPower+","oldValue":"35","newValue":"40"},{"stat":"Speed","oldValue":"5.00","newValue":"5.00"},{"stat":"Life","oldValue":"1814","newValue":"1814"},{"stat":"Atk1","oldValue":"655","newValue":"786"},{"stat":"Atk1+","oldValue":"1087","newValue":"1287"},{"stat":"Atk2","oldValue":"655","newValue":"786"},{"stat":"Atk2+","oldValue":"1087","newValue":"1287"}] },
        { "name": "King Lulu", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_bc_10.png", "changes": [{"stat":"AbilityPower","oldValue":"25","newValue":"25"},{"stat":"AbilityPower+","oldValue":"48","newValue":"40"},{"stat":"Speed","oldValue":"3.57","newValue":"3.45"},{"stat":"Life","oldValue":"1981","newValue":"1981"},{"stat":"Atk1","oldValue":"813","newValue":"1113"},{"stat":"Atk1+","oldValue":"1244","newValue":"1644"},{"stat":"Atk2","oldValue":"813","newValue":"1113"},{"stat":"Atk2+","oldValue":"1244","newValue":"1644"}] },
        { "name": "Altaris", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_ca_10.png", "changes": [{"stat":"AbilityPower","oldValue":"20","newValue":"20"},{"stat":"AbilityPower+","oldValue":"30","newValue":"35"},{"stat":"Speed","oldValue":"3.33","newValue":"3.33"},{"stat":"Life","oldValue":"2315","newValue":"2315"},{"stat":"Atk1","oldValue":"938","newValue":"1238"},{"stat":"Atk1+","oldValue":"1407","newValue":"1907"},{"stat":"Atk2","oldValue":"938","newValue":"1238"},{"stat":"Atk2+","oldValue":"1407","newValue":"1907"}] },
        { "name": "Mad Mike", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_de_10.png", "changes": [{"stat":"AbilityPower","oldValue":"20","newValue":"25"},{"stat":"AbilityPower+","oldValue":"50","newValue":"45"},{"stat":"Speed","oldValue":"5.88","newValue":"6.25"},{"stat":"Life","oldValue":"1591","newValue":"1591"},{"stat":"Atk1","oldValue":"611","newValue":"611"},{"stat":"Atk1+","oldValue":"917","newValue":"917"},{"stat":"Atk2","oldValue":"611","newValue":"611"},{"stat":"Atk2+","oldValue":"917","newValue":"917"}] },
        { "name": "Yggdrasil", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_fb_10.png", "changes": [{"stat":"AbilityPower","oldValue":"15","newValue":"15"},{"stat":"AbilityPower+","oldValue":"20","newValue":"25"},{"stat":"Speed","oldValue":"3.85","newValue":"3.85"},{"stat":"Life","oldValue":"2217","newValue":"2617"},{"stat":"Atk1","oldValue":"746","newValue":"746"},{"stat":"Atk1+","oldValue":"1120","newValue":"1155"},{"stat":"Atk2","oldValue":"746","newValue":"746"},{"stat":"Atk2+","oldValue":"1120","newValue":"1155"}] },
        { "name": "Ossembly", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_b_12.png", "changes": [{"stat":"AbilityPower","oldValue":"30","newValue":"50"},{"stat":"AbilityPower+","oldValue":"50","newValue":"75"},{"stat":"Speed","oldValue":"6.25","newValue":"6.25"},{"stat":"Life","oldValue":"1680","newValue":"1680"},{"stat":"Atk1","oldValue":"719","newValue":"719"},{"stat":"Atk1+","oldValue":"1131","newValue":"1131"},{"stat":"Atk2","oldValue":"719","newValue":"719"},{"stat":"Atk2+","oldValue":"1131","newValue":"1131"}] },
        { "name": "Howlosaurus", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_d_12.png", "changes": [{"stat":"AbilityPower","oldValue":"22","newValue":"22"},{"stat":"AbilityPower+","oldValue":"40","newValue":"40"},{"stat":"Speed","oldValue":"3.33","newValue":"3.33"},{"stat":"Life","oldValue":"2158","newValue":"2158"},{"stat":"Atk1","oldValue":"485:AOE","newValue":"585:AOE"},{"stat":"Atk1+","oldValue":"828:AOE","newValue":"928:AOE"},{"stat":"Atk2","oldValue":"844","newValue":"924"},{"stat":"Atk2+","oldValue":"1360","newValue":"1470"}] },
        { "name": "Data Snail", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_da_12.png", "changes": [{"stat":"AbilityPower","oldValue":"25","newValue":"25"},{"stat":"AbilityPower+","oldValue":"50","newValue":"50"},{"stat":"Speed","oldValue":"3.64","newValue":"3.64"},{"stat":"Life","oldValue":"2995","newValue":"2995"},{"stat":"Atk1","oldValue":"855","newValue":"1085"},{"stat":"Atk1+","oldValue":"1329","newValue":"1629"},{"stat":"Atk2","oldValue":"855","newValue":"1085"},{"stat":"Atk2+","oldValue":"1329","newValue":"1629"}] },
        { "name": "Sidereal Explorer", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_e_12.png", "changes": [{"stat":"AbilityPower","oldValue":"15","newValue":"15"},{"stat":"AbilityPower+","oldValue":"30","newValue":"30"},{"stat":"Speed","oldValue":"4.55","newValue":"4.55"},{"stat":"Life","oldValue":"1803","newValue":"1753"},{"stat":"Atk1","oldValue":"527:AOE","newValue":"527:AOE"},{"stat":"Atk1+","oldValue":"791:AOE","newValue":"891:AOE"},{"stat":"Atk2","oldValue":"542:AOE","newValue":"542:AOE"},{"stat":"Atk2+","oldValue":"811:AOE","newValue":"911:AOE"}] },
        { "name": "Summoner", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_f_12.png", "changes": [{"stat":"AbilityPower","oldValue":"15","newValue":"20"},{"stat":"AbilityPower+","oldValue":"25","newValue":"30"},{"stat":"Speed","oldValue":"8.33","newValue":"8.33"},{"stat":"Life","oldValue":"1590","newValue":"1590"},{"stat":"Atk1","oldValue":"477","newValue":"477"},{"stat":"Atk1+","oldValue":"722","newValue":"762"},{"stat":"Atk2","oldValue":"488","newValue":"488"},{"stat":"Atk2+","oldValue":"738","newValue":"798"}] },
        { "name": "Simurgh", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_fd_12.png", "changes": [{"stat":"AbilityPower","oldValue":"15","newValue":"15"},{"stat":"AbilityPower+","oldValue":"20","newValue":"20"},{"stat":"Speed","oldValue":"7.14","newValue":"8.33"},{"stat":"Life","oldValue":"1399","newValue":"1399"},{"stat":"Atk1","oldValue":"687","newValue":"687"},{"stat":"Atk1+","oldValue":"1030","newValue":"1030"},{"stat":"Atk2","oldValue":"515","newValue":"515"},{"stat":"Atk2+","oldValue":"515:AOE","newValue":"515:AOE"}] },
        { "name": "The Phosphorescent", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_bb_13.png", "changes": [{"stat":"AbilityPower","oldValue":"15","newValue":"15"},{"stat":"AbilityPower+","oldValue":"40","newValue":"40"},{"stat":"Speed","oldValue":"4.00","newValue":"4.17"},{"stat":"Life","oldValue":"2833","newValue":"2833"},{"stat":"Atk1","oldValue":"1011","newValue":"1011"},{"stat":"Atk1+","oldValue":"1553","newValue":"1553"},{"stat":"Atk2","oldValue":"586:AOE","newValue":"586:AOE"},{"stat":"Atk2+","oldValue":"1077:AOE","newValue":"1077:AOE"}] },
        { "name": "Frozen Emperor", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_df_13.png", "changes": [{"stat":"AbilityPower","oldValue":"17","newValue":"30"},{"stat":"AbilityPower+","oldValue":"35","newValue":"45"},{"stat":"Speed","oldValue":"4.55","newValue":"4.55"},{"stat":"Life","oldValue":"1844","newValue":"1974"},{"stat":"Atk1","oldValue":"770","newValue":"770"},{"stat":"Atk1+","oldValue":"1496","newValue":"1496"},{"stat":"Atk2","oldValue":"770","newValue":"770"},{"stat":"Atk2+","oldValue":"1155:AOE","newValue":"1155:AOE"}] },
        { "name": "Hekatoncheiros", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_ec_13.png", "changes": [{"stat":"AbilityPower","oldValue":"20","newValue":"20"},{"stat":"AbilityPower+","oldValue":"35","newValue":"35"},{"stat":"Speed","oldValue":"3.39","newValue":"3.39"},{"stat":"Life","oldValue":"2425","newValue":"2425"},{"stat":"Atk1","oldValue":"1078","newValue":"1078"},{"stat":"Atk1+","oldValue":"1742","newValue":"1842"},{"stat":"Atk2","oldValue":"1078","newValue":"1078"},{"stat":"Atk2+","oldValue":"1742","newValue":"1842"}] },
        { "name": "Black I.C.E", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_af_14.png", "changes": [{"stat":"AbilityPower","oldValue":"10","newValue":"10"},{"stat":"AbilityPower+","oldValue":"50","newValue":"50"},{"stat":"Speed","oldValue":"10.00","newValue":"10.00"},{"stat":"Life","oldValue":"1241","newValue":"1351"},{"stat":"Atk1","oldValue":"687","newValue":"687"},{"stat":"Atk1+","oldValue":"975","newValue":"975"},{"stat":"Atk2","oldValue":"687","newValue":"687"},{"stat":"Atk2+","oldValue":"975","newValue":"975"}] },
        { "name": "Greensward Rager", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_bd_14.png", "changes": [{"stat":"AbilityPower","oldValue":"30","newValue":"30"},{"stat":"AbilityPower+","oldValue":"50","newValue":"50"},{"stat":"Speed","oldValue":"4.44","newValue":"4.65"},{"stat":"Life","oldValue":"2386","newValue":"2386"},{"stat":"Atk1","oldValue":"684","newValue":"684"},{"stat":"Atk1+","oldValue":"1086","newValue":"1086"},{"stat":"Atk2","oldValue":"684","newValue":"684"},{"stat":"Atk2+","oldValue":"1086","newValue":"1086"}] },
        { "name": "Gladiator", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_c_14.png", "changes": [{"stat":"AbilityPower","oldValue":"20","newValue":"30"},{"stat":"AbilityPower+","oldValue":"30","newValue":"45"},{"stat":"Speed","oldValue":"4.35","newValue":"4.35"},{"stat":"Life","oldValue":"2144","newValue":"2224"},{"stat":"Atk1","oldValue":"1124","newValue":"1124"},{"stat":"Atk1+","oldValue":"1443","newValue":"1443"},{"stat":"Atk2","oldValue":"833:AOE","newValue":"833:AOE"},{"stat":"Atk2+","oldValue":"1124:AOE","newValue":"1124:AOE"}] },
        { "name": "Breakmaster", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_ca_14.png", "changes": [{"stat":"AbilityPower","oldValue":"10","newValue":"10"},{"stat":"AbilityPower+","oldValue":"20","newValue":"20"},{"stat":"Speed","oldValue":"5.00","newValue":"4.76"},{"stat":"Life","oldValue":"2766","newValue":"2466"},{"stat":"Atk1","oldValue":"1233","newValue":"1233"},{"stat":"Atk1+","oldValue":"2024","newValue":"2024"},{"stat":"Atk2","oldValue":"870:AOE","newValue":"870:AOE"},{"stat":"Atk2+","oldValue":"1477:AOE","newValue":"1477:AOE"}] },
        { "name": "Magican", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_f_14.png", "changes": [{"stat":"AbilityPower","oldValue":"20","newValue":"25"},{"stat":"AbilityPower+","oldValue":"35","newValue":"35"},{"stat":"Speed","oldValue":"5.56","newValue":"5.88"},{"stat":"Life","oldValue":"1741","newValue":"1691"},{"stat":"Atk1","oldValue":"784","newValue":"784"},{"stat":"Atk1+","oldValue":"1134","newValue":"1134"},{"stat":"Atk2","oldValue":"531:AOE","newValue":"531:AOE"},{"stat":"Atk2+","oldValue":"784:AOE","newValue":"784:AOE"}] },
        { "name": "Spectroplasm", "image": "https://s-ak.kobojo.com/mutants/assets/thumbnails/specimen_b_14.png", "changes": [{"stat":"AbilityPower","oldValue":"30","newValue":"30"},{"stat":"AbilityPower+","oldValue":"40","newValue":"40"},{"stat":"Speed","oldValue":"5.41","newValue":"5.41"},{"stat":"Life","oldValue":"1951","newValue":"1951"},{"stat":"Atk1","oldValue":"721","newValue":"721"},{"stat":"Atk1+","oldValue":"1029","newValue":"1029"},{"stat":"Atk2","oldValue":"561:AOE","newValue":"561:AOE"},{"stat":"Atk2+","oldValue":"721:AOE","newValue":"721:AOE"}] }
      ]
    }
  ];

  /* ── Helpers ─────────────────────────────────────── */
  function getChangeClass(oldVal, newVal) {
    const o = parseFloat(oldVal);
    const n = parseFloat(newVal);
    if (isNaN(o) || isNaN(n)) return 'info';
    if (n > o) return 'up';
    if (n < o) return 'down';
    return 'same';
  }

  /* ── Render ──────────────────────────────────────── */
  function renderCard(mutant) {
    const changesHtml = mutant.changes.map(c => {
      const cls = getChangeClass(c.oldValue, c.newValue);
      const showOld = c.oldValue !== c.newValue;
      return `
        <div class="rb-change-row">
          <span class="rb-stat-name">${c.stat}</span>
          <div class="rb-change-values">
            ${showOld ? `<span class="rb-old-val">${c.oldValue}</span><span class="rb-arrow">→</span>` : ''}
            <span class="rb-new-val ${cls}">${c.newValue}</span>
          </div>
        </div>`;
    }).join('');

    return `
      <div class="rb-card">
        <div class="rb-card-header">
          <img src="${mutant.image}" alt="${_rbGetName(mutant)}" class="rb-avatar"
               onerror="this.style.opacity='0.2'">
          <span class="rb-card-name">${_rbGetName(mutant)}</span>
        </div>
        <div class="rb-changes">${changesHtml}</div>
      </div>`;
  }

  function renderMonth(monthData, idx) {
    const cards = monthData.mutants.map(renderCard).join('');
    // First accordion open by default
    const openClass = idx === 0 ? ' open' : '';
    const bodyStyle = idx === 0 ? '' : 'style="display:none"';
    return `
      <div class="rb-accordion${openClass}" data-accordion="${idx}">
        <div class="rb-accordion-header" onclick="rbToggle(${idx})">
          <div class="rb-accordion-left">
            <div class="rb-accordion-icon">
              <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                <circle cx="12" cy="12" r="3"/>
                <path d="M19.07 4.93a10 10 0 0 1 0 14.14M4.93 4.93a10 10 0 0 0 0 14.14"/>
              </svg>
            </div>
            <span class="rb-accordion-title">${monthData.title}</span>
          </div>
          <div class="rb-accordion-right">
            <span class="rb-month-badge">${monthData.mutants.length} mutantes</span>
            <svg class="rb-chevron" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
              <polyline points="6 9 12 15 18 9"/>
            </svg>
          </div>
        </div>
        <div class="rb-accordion-body" ${bodyStyle}>
          <div class="rb-grid">${cards}</div>
        </div>
      </div>`;
  }

  /* ── Toggle ──────────────────────────────────────── */
  window.rbToggle = function(idx) {
    const el = document.querySelector(`[data-accordion="${idx}"]`);
    if (!el) return;
    const body = el.querySelector('.rb-accordion-body');
    const isOpen = el.classList.contains('open');
    if (isOpen) {
      el.classList.remove('open');
      body.style.display = 'none';
    } else {
      el.classList.add('open');
      body.style.display = 'block';
    }
  };

  /* ── Mount ───────────────────────────────────────── */
  const container = document.getElementById('rebalance-section');
  if (!container) return;

  const renderAll = () => ALL_REBALANCE_DATA.map((month, i) => renderMonth(month, i)).join('');
  container.innerHTML = renderAll();

  // Re-render mutant names when language changes
  if (typeof MGG !== 'undefined' && MGG.onLangChange) {
    MGG.onLangChange(() => { container.innerHTML = renderAll(); });
  }
});
