[[redirects]]
  from = "/mutants-list"
  to = "/mutants-list.html"
  status = 200

[[redirects]]
  from = "/stats"
  to = "/stats.html"
  status = 200

[[redirects]]
  from = "/evo-calculator"
  to = "/evo-calculator.html"
  status = 200

[[redirects]]
  from = "/top-mutants"
  to = "/top-mutants.html"
  status = 200

[[redirects]]
  from = "/damage-simulator"
  to = "/damage-simulator.html"
  status = 200

[[redirects]]
  from = "/mutant-builder"
  to = "/mutant-builder.html"
  status = 200

[[redirects]]
  from = "/compare"
  to = "/compare.html"
  status = 200

[[redirects]]
  from = "/rebalance"
  to = "/rebalance.html"
  status = 200

[[redirects]]
  from = "/credits"
  to = "/credits.html"
  status = 200

[[redirects]]
  from = "/changelog"
  to = "/changelog.html"
  status = 200

[[redirects]]
  from = "/maintenance"
  to = "/maintenance.html"
  status = 200

[[redirects]]
  from = "/maintenance-section"
  to = "/maintenance-section.html"
  status = 200

[[redirects]]
  from = "/404"
  to = "/404.html"
  status = 200
